# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: remove cnca golang cache folder
  file:
    path: "{{ offline_path }}/golang_modules/cnca"
    state: absent

- name: create empty cnca golang cache folder
  file:
    path: "{{ offline_path }}/golang_modules/cnca"
    state: directory

- name: download cnca golang modules
  block:
    - include_tasks: ../../../git_repo/tasks/gitconfig_bootstrap.yml
    - name: download modules
      shell: "PATH=$PATH:/usr/local/go/bin GOPATH={{ offline_path }}/golang_modules/cnca go mod download"
      args:
        chdir: "{{ git_repo_dest }}/cnca"
  always:
    - include_tasks: ../../../git_repo/tasks/gitconfig_remove.yml
