---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: addons
  namespace: flux-system
spec:
  interval: 5m
  path: deploy/site/cluster-addons
  prune: true
  sourceRef:
    kind: GitRepository
    name: icn
  wait: true
  timeout: 10m
  patches:
  - patch: |
      - op: add
        path: /spec/healthChecks/-
        value:
          apiVersion: helm.toolkit.fluxcd.io/v2beta1
          kind: HelmRelease
          name: monitor
          namespace: emco
      - op: add
        path: /spec/healthChecks/-
        value:
          apiVersion: helm.toolkit.fluxcd.io/v2beta1
          kind: HelmRelease
          name: services
          namespace: emco
      - op: add
        path: /spec/healthChecks/-
        value:
          apiVersion: helm.toolkit.fluxcd.io/v2beta1
          kind: HelmRelease
          name: tools
          namespace: emco
    target:
      kind: Kustomization
      name: sriov-network-operator
      namespace: kud
