---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: emco-compute
  namespace: flux-system
spec:
  interval: 5m
  path: deploy/site/cluster-emco-compute
  prune: true
  sourceRef:
    kind: GitRepository
    name: icn
  wait: true
  timeout: 10m
