---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: emco-management
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: icn-master-sops-gpg
  interval: 5m
  path: deploy/site/cluster-emco-management
  prune: true
  sourceRef:
    kind: GitRepository
    name: icn
  wait: true
  timeout: 10m
