# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: kube-ovn cleanup
  block:
  - name: download kube-ovn cleanup script
    get_url:
      url: "{{ kubeovn_cleanup_url }}"
      dest: "{{ kubeovn_cleanup_dest }}"
      mode: 0755
  - name: change hardcoded tag
    replace:
      path: "{{ kubeovn_cleanup_dest }}"
      regexp: "kube-ovn/master"
      replace: "kube-ovn/{{ kubeovn_version }}"
  - name: execute kube-ovn cleanup script
    shell: "timeout 120 {{ kubeovn_cleanup_dest }}"
    ignore_errors: yes
  - name: remove ovs/ovn related files
    file:
      path: "{{ item }}"
      state: absent
    with_items: "{{ kubeovn_cleanup_paths }}"
