---
apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
  namespace: default
data:
  # Key value corresponds to a user name defined in Ceph cluster
  admin: "QVFBUmlxbGQ3bk5JQ3hBQVo3ekpvZHBj2tVaWlDczlN3NVSUE9PQ=="
  # Key value corresponds to a user name defined in Ceph cluster
  kube: "QVFCVm1hbGRjNGpGRnhBQWRvaVFrdG8xWFR6RmxOdmFBKzJoaEE9PQ=="
  # if monValueFromSecret is set to "monitors", uncomment the
  # following and set the mon there
  #monitors: BASE64-ENCODED-Comma-Delimited-Mons
