---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tools
  namespace: emco
spec:
  interval: 5m
  chart:
    spec:
      chart: deployments/helm/emcoOpenNESS/emco-tools
      sourceRef:
        kind: GitRepository
        name: emco
      interval: 1m
  timeout: 10m
  dependsOn:
  - name: podsecurity
  values:
    global:
      repository: integratedcloudnative/
      pullPolicy: IfNotPresent
    fluentd:
      clusterDomain: cluster.local
