apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: db
    namespace: emco
spec:
    interval: 5m
    chart:
        spec:
            chart: deployments/helm/emcoBase/emco-db
            sourceRef:
                kind: GitRepository
                name: emco
            interval: 1m
    timeout: 10m
    install:
        remediation:
            retries: -1
    upgrade:
        remediation:
            retries: -1
    dependsOn:
        - name: podsecurity
    values:
        global:
            repository: integratedcloudnative/
            pullPolicy: IfNotPresent
            db:
                rootPassword: ENC[AES256_GCM,data:lVFVEBepSTbjVaIM10Qi6w==,iv:f1Ud8E1I6y47IVQZ6HyQBm2GdmYfpRGOJDI+VHzkDVk=,tag:utWhcxk4KxkgtMIuJ7JfJg==,type:str]
                emcoPassword: ENC[AES256_GCM,data:qPj/L7dp6ChqQROipHBHBw==,iv:OEcr5AZq3oS6573UIZcizKJ0HNWZoe/DdlhxUxtpMvc=,tag:Wc8eKl+JgJmUdlAiU0D/pQ==,type:str]
            contextdb:
                rootPassword: ENC[AES256_GCM,data:9/cBu0p/voFS5y/2QVfZVg==,iv:ljzTeDW1pbkRdrD9MnrewejQ/bamj6DK82zb668GILY=,tag:ogqvHV2zxQZwUDhdIS7gzA==,type:str]
        etcd:
            clusterDomain: cluster.local
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-18T16:50:53Z"
    mac: ENC[AES256_GCM,data:Umh9SeSRqFBfJHeXAiD02T+8gil2jPft0Dr8itSjX36ah/sOW0sQWiG4ktNDVLA9d9XBNH1g9MJFbasHM1h6E7L0hLhgS06DOc8fK1QZNAtmzqR3ygtnzuYQCSFwj2TLwwQhz2AuH8RKHGquJlgFO1Ja7v8VajAEIGOC7YyaljE=,iv:Q6L44pqfDxc0cXHlwm2vDOTWRDfQPU6Z3OJFZXYD4ZU=,tag:VwAm8JORXdUdOi/tFMGpnA==,type:str]
    pgp:
        - created_at: "2022-01-18T16:50:51Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4SX7nk+q+zPAQ//WDlequVQ5bIaWl+QjrPjt236Px/oyxyhZfUBNxryOspQ
            hwrGmHXLxL5+/EEyMexmDxKzQWmQQQsX81Gy5ME26dPIWcM5Nkgtm4vndLBJ0fbK
            NtOTtBk6WZMoyaIPqN9zzdKNUQcjJt3Nwt7UN6V/f4ce6nXsvrMNU51sApu2USyw
            TrSIfl28pNceelERPhQqvyT90iX9yd64nSeQC3osomiYHGhvuHMVTrEpleO023OD
            AA9ZoUoqAWQNnoSfiYPmrjnYf0T71RTrPCQd1B6yriJvp+rEwS7Y98wNhBP+DAwm
            n/ascvrhdbMieILygC6rByOI51NWL9n/iC4U3mIZItN7WPWSHLfn49oJ0TUBZ1P1
            cS1+L5cb7lzJ08BGEy583ZOVQPrtvVIGkcWueD1LV6l8yfSz0SxsBkmoGAybh1PC
            SpcCXHmF3hYhc1Klq+IiGDRlZe5T0q9L0P5nwIwqwoeXuIpBMcIreUhgUWwserMw
            hqf53ye4bZt/FY5pCRTqZ5Oe+3tjS/RPGPSu6bY4UUThMu3Blo+U+6NQJRNPGmht
            NP4ecu/EJDk+JfafzZtuoF/H97JlOqR9Zxf9JZgVPB7xrbV3romhtXIEUU97i/rS
            mFEg5Th3mV9TqSuBMROeErBWsnnCikRtQl4CrpphBGgx+XhmRVIyibLqWSTBytvS
            XgEj6F3GJfakhzxEc5Bv7zH2DSrjS4cwqdjkcVHgqDjJVk+wvHXFKdaDqm9FOH87
            nk5JsJHcTEV1m9Sga3nPI5WuBPd3J5yABh4uEoGy8d4uW3unYisWOHyDRLHE6bU=
            =YZiN
            -----END PGP MESSAGE-----
          fp: A4B4A47A1DB07DE00E8158BE411E23534CA8FAE0
    encrypted_regex: ^(bmcPassword|decryptionSecret|hashedPassword|emcoPassword|rootPassword)$
    version: 3.7.1
