---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tools
  namespace: emco
spec:
  interval: 5m
  chart:
    spec:
      chart: deployments/helm/emcoBase/emco-tools
      sourceRef:
        kind: GitRepository
        name: emco
      interval: 1m
  timeout: 10m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  dependsOn:
  - name: podsecurity
  values:
    global:
      repository: registry.gitlab.com/project-emco/core/emco-base/
      pullPolicy: IfNotPresent
    fluentd:
      clusterDomain: cluster.local
