---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kata
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./deploy/kata/icn
  prune: true
  sourceRef:
    kind: GitRepository
    name: icn
  wait: true
  timeout: 10m
