---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubevirt
  namespace: kud
spec:
  interval: 5m
  chart:
    spec:
      chart: kud/deployment_infra/helm/kubevirt
      sourceRef:
        kind: GitRepository
        name: kud
      interval: 1m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  dependsOn:
  - name: kubevirt-operator
