---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sriov-network
  namespace: kud
spec:
  interval: 5m
  chart:
    spec:
      chart: kud/deployment_infra/helm/sriov-network
      sourceRef:
        kind: GitRepository
        name: kud
      interval: 1m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  # Deployment of sriov-network causes the SR-IOV operator to drain
  # the node, including the Flux controllers.  If the Helm controller
  # is restarted while a chart install is pending, it is possible that
  # the chart state becomes stuck in "pending-install" and manual
  # intervention (deleting the Helm secret for the chart) is required
  # to fix it.  Depending on the other charts in this cluster should
  # prevent this issue from occurring.
  dependsOn:
  - name: cdi
  - name: cpu-manager
  - name: kubevirt
  - name: ovn4nfv-network
  - name: ovn4nfv
  - name: node-feature-discovery
  - name: qat-device-plugin
  - name: sriov-network-operator
  - namespace: emco
    name: services
  - namespace: emco
    name: tools
  - namespace: emco
    name: monitor
