---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sriov-network
  namespace: kud
spec:
  interval: 5m
  chart:
    spec:
      chart: kud/deployment_infra/helm/sriov-network
      sourceRef:
        kind: GitRepository
        name: kud
      interval: 1m
  dependsOn:
  - name: sriov-network-operator
