---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitor
  namespace: emco
spec:
  interval: 5m
  chart:
    spec:
      chart: deployments/helm/monitor
      sourceRef:
        kind: GitRepository
        name: emco
      interval: 1m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  values:
    registryPrefix: registry.gitlab.com/project-emco/core/emco-base/
    tag: "22.03"
