# The dictionary of clusters to create.
clusters:
  # The cluster name.
  ha-dhcp:

    # Example provider and site labels; additional labels may be
    # provided.
    clusterLabels:
      provider: icn
      site: test-site

    # The number of control plane nodes.
    numControlPlaneMachines: 3

    # The number of worker nodes.
    numWorkerMachines: 2

    # The control plane endpoint of the cluster.  This is a virtual IP
    # managed by keepalived.
    controlPlaneEndpoint: 192.168.151.254
    controlPlanePrefix: 24

    # keepalived uses the VRRP protocol to assign the control plane
    # endpoint among the control plane nodes.
    keepalived:
      # This interface must be the same as the baremetal interface.
      interface: ens6
      routerId: 3

    # Since DHCP is present, the network configuration of each machine
    # may be provided with a template containing the names of the
    # baremetal and provisioning interfaces.
    networks:
      baremetal:
        interface: ens6
      provisioning:
        interface: ens5

    # The user account created in all the machines.
    userData:
      name: ubuntu
      # mkpasswd --method=SHA-512 --rounds 4096 "mypasswd"
      hashedPassword: $6$rounds=4096$acxyX2VqfHJSAc2$sgVf5uTHHPCX6u50NHnJmhIoqbcL9J12jlBAaWKvd3w8uYO0iXgcBrEhtvHLgSGU7dcU.eqm9JwXEYbbRjPAi1
      # This key will also be authorized to login as the root user
      sshAuthorizedKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCrxu+fSrU51vgAO5zP5xWcTU8uLv4MkUZptE2m1BJE88JdQ80kz9DmUmq2AniMkVTy4pNeUW5PsmGJa+anN3MPM99CR9I37zRqy5i6rUDQgKjz8W12RauyeRMIBrbdy7AX1xasoTRnd6Ta47bP0egiFb+vUGnlTFhgfrbYfjbkJhVfVLCTgRw8Yj0NSK16YEyhYLbLXpix5udRpXSiFYIyAEWRCCsWJWljACr99P7EF82vCGI0UDGCCd/1upbUwZeTouD/FJBw9qppe6/1eaqRp7D36UYe3KzLpfHQNgm9AzwgYYZrD4tNN6QBMq/VUIuam0G1aLgG8IYRLs41HYkJ root@jump

    # Flux bootstrapping of the cluster.  When enabled, the Flux
    # controllers will be installed into the cluster and begin
    # reconciling the resources located at the specified location.
    flux:
      repositoryName: icn
      url: https://gerrit.akraino.org/r/icn
      branch: master
      # The path at the repository to the resources to be applied to the
      # cluster
      path: ./deploy/test-site/ha-dhcp

    # The containerRuntime may be containerd or docker.
    containerRuntime: containerd

    # The POD CIDR.
    podCidr: 10.244.64.0/18

    # The only currently supported CNI is flannel.
    cni: flannel

    # All the version info is captured in one block here.  Care must
    # be taken to ensure that the OS, Kubernetes, and CRI (containerd
    # or docker) versions are all compatible.
    #
    # Refer to the below for further information:
    # - https://github.com/kubernetes/kubernetes/blob/master/build/dependencies.yaml
    # - https://download.docker.com/linux/ubuntu/dists/bionic/stable/binary-amd64/Packages
    #
    # The OS image.
    imageName: bionic-server-cloudimg-amd64.img
    # The version of Kubernetes installed.
    k8sVersion: v1.21.6
    # The version of the kubelet, kubeadm, and kubectl packages.
    kubeVersion: 1.21.6-00
    # The version of the CRI installed.
    containerdVersion: 1.4.11-1
    dockerVersion: 5:20.10.10~3-0~ubuntu-bionic
