# The following patch enables conversion webhook for CRD
# CRD conversion requires k8s 1.13 or later.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: firmwareschemas.metal3.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:      
          namespace: system
          name: webhook-service
          path: /convert
        caBundle: Cg==
      conversionReviewVersions:
      - v1
