---
- name: grant jenkins user sudo
  copy:
    content: "jenkins        ALL=(ALL)       NOPASSWD: ALL"
    dest: /etc/sudoers.d/jenkins
    owner: root
    group: root
    mode: '0660'

- name: install and configure vagrant
  block:
    - name: install libvirt and vagrant
      package:
        name: "{{ item }}"
      with_items:
        - libvirt-bin
        - vagrant

    - name: add jenkins user to libvirt and vagrant group
      user:
        name: jenkins
        append: yes
        groups:
          - libvirt

    - name: setup vagrant-libvirt plugin
      shell: vagrant plugin install vagrant-libvirt
      become_user: jenkins
  when: enable_vagrant
  tags: [vagrant]

- name: install packages for lftools log
  package:
    name: "{{ item }}"
  with_items:
    - python3-pip
    - python3-venv
    - facter
    - sysstat

- name: enable sysstat
  lineinfile:
    path: /etc/default/sysstat
    regexp: '^ENABLED='
    line: ENABLED="true"

- name: start sysstat service
  service:
    name: sysstat
    state: restarted
