---
- name: grant jenkins user sudo
  copy:
    content: "jenkins        ALL=(ALL)       NOPASSWD: ALL"
    dest: /etc/sudoers.d/jenkins
    owner: root
    group: root
    mode: '0660'

block:
  - name: install libvirt and vagrant
    package:
      name: "{{ item }}"
    with_items:
      - libvirt-bin
      - vagrant
  
  - name: setup vagrant-libvirt plugin
    shell: vagrant plugin install vagrant-libvirt
when: enable_vagrant
tags: [vagrant]
