apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: capm3-system
resources:
- ../ironic
configMapGenerator:
- envs:
  - ironic_bmo_configmap.env
  name: ironic-bmo-configmap
secretGenerator:
- literals:
  - password=changeme
  name: mariadb-password
  type: Opaque