# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: Remove firewall rule for AF port
  shell: firewall-cmd --permanent --direct --remove-rule ipv4 filter INPUT 0 -p tcp --dport 8050 -j ACCEPT
  ignore_errors: yes

- name: Remove firewall rule for AF port
  shell: firewall-cmd --permanent --direct --remove-rule ipv4 filter INPUT 0 -p tcp --dport 8051 -j ACCEPT
  ignore_errors: yes

- name: Reload firewall rules
  shell: firewall-cmd --reload 
  changed_when: false
  ignore_errors: yes

