# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- set_fact:
    grub_file_path: "/boot/grub2/grub.cfg"

- name: check if host is using EFI
  stat:
    path: /sys/firmware/efi
  register: efi_sys_dir

- debug:
    msg: "EFI detected"
  when: efi_sys_dir.stat.exists and efi_sys_dir.stat.isdir == true

- set_fact:
    grub_file_path: "/boot/efi/EFI/centos/grub.cfg"
  when: efi_sys_dir.stat.exists and efi_sys_dir.stat.isdir == true

- debug:
    msg: "grub.cfg file path set to: {{ grub_file_path }}"

- name: set RT kernel as default in grub config
  shell: grubby --set-default /boot/vmlinuz-{{ os_kernel_rt_package_version }}

- name: add GRUB_CMDLINE_LINUX_DEFAULT variable with reqired values
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: "GRUB_CMDLINE_LINUX_DEFAULT=\"{{ os_kernel_rt_grub_parameters }}\""
    insertafter: EOF

- name: regenerate grub.cfg 
  shell: "grub2-mkconfig -o {{ grub_file_path }}" 
