# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: Setup repository
  include_tasks: setup_repository.yml

- name: Install correct tuned packages
  yum:
    name: "{{ os_kernel_rt_tuned_package_urls | join(',') }}"
    state: present
    allow_downgrade: yes
  when: not offline_mode

- name: Install correct tuned package - offline
  yum:
    name: "{{ item.split('/')[-1] | regex_replace('.rpm$') }}"
    state: present
    allow_downgrade: yes
  with_items: "{{ os_kernel_rt_tuned_package_urls }}"
  when: offline_mode

- debug:
    msg: "kernel version to install: {{ os_kernel_rt_package_name }}-{{ os_kernel_rt_package_version }}"

- name: Install required RT kernel
  yum:
    name: "{{ item }}"
    state: present
    disable_excludes: all
  with_items:
    - "{{ os_kernel_rt_package_name }}-{{ os_kernel_rt_package_version }}"
    - "kernel-rt-devel-{{ os_kernel_rt_package_version }}"

- name: Set RT kernel as default
  shell: grubby --set-default /boot/vmlinuz-{{ os_kernel_rt_package_version }}

- name: Copy tuned realtime profile config
  copy:
    content: "{{ os_kernel_rt_tuned_vars }}"
    dest: /etc/tuned/realtime-variables.conf
    owner: root
    group: root
    mode: 0644

- name: Configure GRUB for new kernel
  include_role:
    name: grub
  vars:
    tuned_rt: true

- name: Reboot the machine if still needed
  block:
  # because grub role does reboot as well we might have already booted with proper kernel
  - name: refresh ansible_kernel
    setup:
      filter: ansible_kernel
  - name: Reboot the machine if still needed
    reboot:
    when: ansible_kernel != os_kernel_rt_package_version
