# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: Add firewall rules for Docker containers traffic (syslog)
  shell: firewall-cmd --permanent --direct --add-rule ipv4 filter INPUT 0 -i virbr0 -s 192.168.122.0/24 -d 192.168.122.1 -p tcp --dport 80 -j ACCEPT

- name: Add firewall rules for Docker containers traffic (eaa http)
  shell: firewall-cmd --permanent --direct --add-rule ipv4 filter INPUT 0 -i virbr0 -s 192.168.122.0/24 -d 192.168.122.1 -p tcp --dport 443 -j ACCEPT

- name: Add firewall rules for Docker containers traffic (eaa https)
  shell: firewall-cmd --permanent --direct --add-rule ipv4 filter INPUT 0 -i virbr0 -s 192.168.122.0/24 -d 192.168.122.1 -p udp --dport 514 -j ACCEPT

- name: Add firewall rules for Docker containers traffic (eva)
  shell: firewall-cmd --permanent --direct --add-rule ipv4 filter INPUT 0 -i virbr0 -s 192.168.122.0/24 -d 192.168.122.1 -p udp --dport 42103 -j ACCEPT

- name: Reload firewall rules
  shell: firewall-cmd --reload 
  changed_when: false
