# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: copy logrotate config file for rotating /var/log/appliance files
  copy:
    src: appliance
    dest: /etc/logrotate.d/
    remote_src: no
