# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: Generate empty cert and key file
  file:
    path: "{{ item }}"
    state: touch
    owner: root
    group: root
    mode: 600
  with_items:
    - "/var/lib/appliance/certs/key.pem"
    - "/var/lib/appliance/certs/cert.pem"
