# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: Docker directory (nts)
  file:
    path: /var/lib/appliance/nts
    state: directory

- name: Docker directory (nts/qemu)
  file:
    path: /var/lib/appliance/nts/qemu
    state: directory
    group: kvm
    mode: g+s

- name: Docker directory (edgednssvr)
  file:
    path: /var/lib/appliance/edgednssvr
    state: directory

- name: certificates folder
  file:
    path: /var/lib/appliance/certs
    state: directory
