# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: create customized /etc/docker/daemon.json file
  copy:
    src: "{{ role_path }}/files/docker-daemon.json"
    dest: /etc/docker/daemon.json
    remote_src: no
