# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: Add a TAP interface for EdgeDNS
  shell: >
    ip tuntap del mode tap edgedns-tap &&
    ip tuntap add mode tap edgedns-tap &&
    ip a a 192.168.122.128/24 dev edgedns-tap &&
    brctl addif virbr0 edgedns-tap
