# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- include_tasks: remove_virbr0_interface.yml

# Stop and remove network
- virt_net:
    command: destroy
    name: default
    state: absent

# Create new network config file
- virt_net:
    command: define
    name: default
    xml: '{{ lookup("file", "files/libvirt-default.xml") }}'

# Enable now
- virt_net:
    name: default
    state: active

# Activate at boot
- virt_net:
    name: default
    autostart: yes
