# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: remove keys and certificates
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ git_repo_dest }}/certs/key.pem"
    - "{{ git_repo_dest }}/certs/cert.pem"
    - "{{ git_repo_dest }}/certs/cacerts.pem"
    - "{{ git_repo_dest }}/certs/root.pem"
