# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: Check Docker service
  shell: systemctl status docker
  ignore_errors: true
  changed_when: false
  args:
    warn: false
  register: docker_service_status

- name: Check Docker images
  shell: docker images -q
  changed_when: false
  register: docker_images_present
  when: docker_service_status.rc == 0
    
- name: Remove Docker images  
  shell: docker rmi -f $(docker images -q)
  when: 
    - docker_service_status.rc == 0
    - docker_images_present.stdout != ''
