# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: check if system virbr0 interface exists
  stat:
    path: /sys/class/net/virbr0
  register: virbr0_interface_result

- name: remove virbr0 interface
  block:
    - name: shut down
      command: ip link set virbr0 down
    - name: remove IP addresses
      command: ip addr flush dev virbr0
    - name: remove interface from system
      command: brctl delbr virbr0
  when: virbr0_interface_result.stat.exists == true
