apiVersion: apps/v1
kind: DaemonSet
metadata:
  name:  iavf-driver-installer
  namespace: kube-system
  labels:
    role: iavf-driver-installer
spec:
  selector:
    matchLabels:
      role: iavf-driver-installer
  template:
    metadata:
      labels:
        role: iavf-driver-installer
    spec:
      hostPID: true
      initContainers:
        - image: "integratedcloudnative/iavf-driver-installer:latest"
          imagePullPolicy: IfNotPresent
          name: iavf-driver-installer
          securityContext:
            privileged: true
          volumeMounts:
            - name: iavf-install-dir
              mountPath: "/usr/local/iavf"
            - name: root-dir
              mountPath: "/root"
            - name: lib-modules-dir
              mountPath: "/root/lib/modules"
            - name: run-systemd-dir
              mountPath: "/root/run/systemd/system"
      containers:
      - image: "gcr.io/google-containers/pause:3.2"
        name: pause
      volumes:
        - name: iavf-install-dir
          hostPath:
            path: "/opt/iavf"
        - name: root-dir
          hostPath:
            path: "/"
        - name: lib-modules-dir
          hostPath:
            path: "/lib/modules"
        - name: run-systemd-dir
          hostPath:
            path: "/run/systemd/system"
      nodeSelector:
        feature.node.kubernetes.io/custom-iavf: "true"
