# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

resources:
- multus-daemonset.yml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: kube-multus-ds-amd64
  path: rename_default_net.yml
