# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: online mode
  block:
    - debug:
        msg: "Using git token for repository checkout"
      when: git_repo_token|bool

    - name: checkout clean repository
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ git_repo_dest }}"
        version: "{{ git_repo_branch }}"
        force: yes
      when: always_clean_repository

    - name: make sure repository exists
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ git_repo_dest }}"
        version: "{{ git_repo_branch }}"
        update: no
      when: not always_clean_repository
  when: not offline_mode

- name: offline mode
  block:
    - name: copy repository to proper path
      copy:
        src: "{{ offline_path }}/{{ git_repo_dest.split('/')[-1] }}"
        dest: "/opt"
        remote_src: yes
  when: offline_mode
