# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

# Deploy OpenNESS Controller on given host

- hosts: controller_group
  vars:
    hugepage_amount: "500"

  pre_tasks:
  - name: fail if more than 1 controller
    fail:
      msg: "Only one controller is supported"
    when:
    - groups['controller_group'] is defined
    - (groups['controller_group']|length>1)
  - include_tasks: ./tasks/precheck_hostname.yml

  roles:
    - role: os_setup
    - role: grub
    - role: git_repo
    - role: golang
    - role: docker
    - role: kubernetes/master
    - role: kubeovn/master
    - role: openness/network_edge/master
    - role: biosfw/master
    - role: multus
    - role: sriov/master
