# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

# Deploy EdgeNode on given host(s)

- hosts: edgenode_group
  serial: 1
  vars:
    hugepage_amount: "500"

  pre_tasks:
  - debug:
      msg: "Setting up {{ inventory_hostname | upper }} at {{ ansible_host }}"
  - include_tasks: ./tasks/precheck_hostname.yml

  roles:
    - role: os_setup
    - role: grub
    - role: git_repo
    - role: golang
    - role: docker
    - role: opae_fpga/worker
    - role: kubernetes/worker
    - role: kubeovn/worker
    - role: openness/network_edge/worker
    - role: biosfw/worker
    - role: sriov/worker
