# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: remove downloaded artifacts
  file:
    name: "{{ item }}"
    state: absent
  with_items:
  - "{{ sriov_cni.download_dir }}"
  - "{{ sriov_dev_plugin.download_dir }}"

- name: remove patch utility
  yum:
    name: patch
    state: absent

# Docker images are removed during Docker's cleanup
