apiVersion: bpa.akraino.org/v1alpha1
kind: Provisioning
metadata:
  name: remote-vvm115
  labels:
    cluster: remote-vvm115
    cluster-type: virtlet-vm
    owner: c1
spec:
  masters:
    - master-1:
        mac-address: c2:b4:57:49:47:f3
    - master-2:
        mac-address: c2:b4:57:49:47:f4
    - master-3:
        mac-address: c2:b4:57:49:47:f5
  workers:
    - worker-1:
        mac-address: c2:b4:57:49:47:f6
    - worker-2:
        mac-address: c2:b4:57:49:47:f7
  PodSubnet: 172.21.64.0/18
