apiVersion: bpa.akraino.org/v1alpha1
kind: Provisioning
metadata:
  name: remote-vvm110
  labels:
    cluster: remote-vvm110
    cluster-type: virtlet-vm
    owner: c1
spec:
  masters:
    - master-1:
        mac-address: c2:b4:57:49:47:f1
  PodSubnet: 172.21.64.0/18
