apiVersion: bpa.akraino.org/v1alpha1
kind: Provisioning
metadata:
  name: bpa-remote
  labels:
    cluster: bpa-remote
    owner: c1
spec:
  masters:
    - remote-compute:
        mac-address:  08:00:27:ef:ab:60
  KUDPlugins:
    - bpa
  PodSubnet: 10.244.64.0/18
