apiVersion: bpa.akraino.org/v1alpha1
kind: Provisioning
metadata:
  name: provisioning-test-bmh
  labels:
    cluster: test-bmh-cluster
    owner: tester
spec:
  masters:
    - pod11-node3:
        mac-address: 00:1e:67:f1:5b:91
  workers:
    - pod11-node2:
        mac-address: 00:1e:67:fe:f4:1a
  KUDPlugins:
    - emco
