# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: Reload udev rules (1/2)
  command: udevadm control --reload-rules

- name: Retrigger udev (2/2)
  command: udevadm trigger
