# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

qemu_version: "4.0.0"
qemu_targets: "x86_64-softmmu"

qemu_name: "qemu-{{ qemu_version }}"
qemu_download_url: "http://download.qemu.org/{{ qemu_name }}.tar.xz"
qemu_download_dest: "/tmp/{{ qemu_name }}.tar.xz"
qemu_install_dir: "/opt/{{ qemu_name }}"
