# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: remove archives folder
  file:
    path: "{{ offline_path }}/archives"
    state: absent

- name: create empty archives folder
  file:
    path: "{{ offline_path }}/archives"
    state: directory

- name: get golang settings
  include_vars: ../../../../golang/defaults/main.yml

- debug:
    msg: "golang will be downloaded from: {{ golang_download_url }}"

- name: download golang package
  get_url:
    url: "{{ golang_download_url }}"
    dest: "{{ offline_path }}/archives/"
