# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

os_kernel_rt_install: false
os_kernel_rt_repository_url: http://linuxsoft.cern.ch/cern/centos/7/rt/CentOS-RT.repo
os_kernel_rt_repository_dest: /etc/yum.repos.d/CentOS-RT.repo
os_kernel_rt_repository_key: http://linuxsoft.cern.ch/cern/centos/7/os/x86_64/RPM-GPG-KEY-cern
os_kernel_rt_repository_key_dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-cern
os_kernel_rt_package_name: "kernel-rt-kvm"
os_kernel_rt_package_version: "3.10.0-957.21.3.rt56.935.el7.x86_64"
os_kernel_rt_tuned_package_urls:
- "http://mirror.centos.org/centos/7/updates/x86_64/Packages/tuned-2.11.0-5.el7_7.1.noarch.rpm"
- "http://lxsoft106.cern.ch/scientific/7x/x86_64/updates/fastbugs/tuned-profiles-realtime-2.11.0-5.el7_7.1.noarch.rpm"

os_kernel_rt_grub_parameters: "hugepagesz=2M hugepages=5000 intel_iommu=on iommu=pt"
os_kernel_rt_tuned_vars: |
  isolated_cores=2-3
  nohz=on
  nohz_full=2-3
