- name: Stop libvirt networks
  virt_net:
    command: destroy
    name: "{{ item.name }}"
    state: inactive
  with_items: "{{ networks }}"
  become: true

- name: Delete libvirt networks
  virt_net:
    command: undefine
    state: absent
    name: "{{ item.name }}"
  with_items: "{{ networks }}"
  become: true

- name: Delete bridges on Ubuntu
  shell: |
     sudo ip link set baremetal down 
     sudo ip link set provisioning down
     ip link del baremetal type bridge | true
     ip link del provisioning type bridge | true

  when:
    - ansible_distribution == 'Ubuntu'

  become: yes

