# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.16.2
controllerManager:
  extraArgs:
    terminated-pod-gc-threshold: "600"
