---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cpu-manager
  namespace: kud
spec:
  interval: 5m
  path: deploy/cpu-manager/icn
  prune: true
  sourceRef:
    kind: GitRepository
    name: icn
    namespace: flux-system
  dependsOn:
  - name: cert-manager
  wait: true
  timeout: 10m
