---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubevirt
  namespace: kud
spec:
  interval: 5m
  path: deploy/kubevirt/icn
  prune: true
  sourceRef:
    kind: GitRepository
    name: icn
    namespace: flux-system
  dependsOn:
  - name: kubevirt-operator
  wait: true
  timeout: 10m
