---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs-cstor
  namespace: openebs
spec:
  interval: 5m
  chart:
    spec:
      chart: deploy/openebs-cstor
      sourceRef:
        kind: GitRepository
        name: icn
        namespace: flux-system
      interval: 1m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  dependsOn:
  - name: openebs
