---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sriov-network-operator
  namespace: kud
spec:
  interval: 5m
  path: deploy/sriov-network-operator/icn
  prune: true
  sourceRef:
    kind: GitRepository
    name: icn
    namespace: flux-system
  dependsOn:
  - name: multus-cni
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: sriov-network-operator
    namespace: kud
  timeout: 10m
