# SPDX-License-Identifier: Apache-2.0
# Copyright © 2019 Intel Corporation

---

- name: remove AF service
  command: kubectl delete service afservice --namespace=ngc
  ignore_errors: yes

- name: remove AF pod
  command: kubectl delete pod af --namespace=ngc
  register: af_pod_removed_status
  ignore_errors: yes

- name: remove AF image
  command: docker image rm -f af-image:1.0
  ignore_errors: yes
  when:
    - af_pod_removed_status.rc == 0

- name: remove NEF service
  command: kubectl delete service nefservice --namespace=ngc
  ignore_errors: yes

- name: remove NEF pod
  command: kubectl delete pod nef --namespace=ngc
  register: nef_pod_removed_status
  ignore_errors: yes

- name: remove NEF image
  command: docker image rm -f nef-image:1.0
  ignore_errors: yes
  when:
    - nef_pod_removed_status.rc == 0

- name: remove OAM service
  command: kubectl delete service oamservice --namespace=ngc
  ignore_errors: yes

- name: remove OAM pod
  command: kubectl delete pod oam --namespace=ngc
  register: oam_pod_removed_status
  ignore_errors: yes

- name: remove OAM image
  command: docker image rm -f oam-image:1.0
  ignore_errors: yes
  when:
    - oam_pod_removed_status.rc == 0

- block:
  - name: output hostname
    command: hostname
    register: hostname_output
  - set_fact:
      k8s_master_node_name: "{{ hostname_output.stdout | lower }}"
  - name: remove label on master node
    command: kubectl label nodes {{ k8s_master_node_name }} 5g-openness=false --overwrite

- name: remove firewall rules
  include_tasks: rm_firewall_rules.yml

