# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: install sql client package
  yum:
    name: mariadb
    state: present

- name: open firewall rules
  ignore_errors: yes
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
  - 8080/tcp
  - 8081/tcp
  - 443/tcp
  - 80/tcp

- name: reload firewall rules
  shell: firewall-cmd --reload
  changed_when: false
