apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gotk-components.yaml

patchesJson6902:
- path: run-as-user-patch.json
  target:
    kind: Deployment
    name: helm-controller
- path: run-as-user-patch.json
  target:
    kind: Deployment
    name: kustomize-controller
- path: run-as-user-patch.json
  target:
    kind: Deployment
    name: notification-controller
- path: run-as-user-patch.json
  target:
    kind: Deployment
    name: source-controller
