# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: create tmp folder
  file:
    path: "{{ offline_path_common }}/tmp"
    state: directory

- name: create extraction script
  template:
    src: extract.sh.j2
    dest: "{{ offline_path_common }}/tmp/extract.sh"
    mode: '0744'

- name: create offline archive
  archive:
    path:
    - "{{ offline_path_common }}/tmp/*"
    dest: "{{ offline_path_common }}/offline-openness.tar"
    format: tar

- name: remove tmp folder
  file:
    path: "{{ offline_path_common }}/tmp"
    state: absent

- debug:
    msg: Offline package was successfully created in {{ offline_path_common }}/offline-openness.tar
