---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cdi-operator
  namespace: kud
spec:
  interval: 5m
  chart:
    spec:
      chart: kud/deployment_infra/helm/cdi-operator
      sourceRef:
        kind: GitRepository
        name: kud
      interval: 1m
  dependsOn:
  - name: podsecurity
