---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cpu-manager
  namespace: kud
spec:
  interval: 5m
  chart:
    spec:
      chart: kud/deployment_infra/helm/cpu-manager
      sourceRef:
        kind: GitRepository
        name: kud
      interval: 1m
  dependsOn:
  - name: podsecurity
