---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emco-db
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: deployments/helm/emcoOpenNESS/emco-db
      sourceRef:
        kind: GitRepository
        name: emco
        namespace: flux-system
      interval: 1m
  releaseName: db
  targetNamespace: emco
  install:
    createNamespace: true
  dependsOn:
  - name: emco-podsecurity
  values:
    global:
      repository: integratedcloudnative/
      pullPolicy: IfNotPresent
    etcd:
      clusterDomain: cluster.local
