---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitor
  namespace: emco
spec:
  interval: 5m
  chart:
    spec:
      chart: deployments/helm/monitor
      sourceRef:
        kind: GitRepository
        name: emco
      interval: 1m
  values:
    registryPrefix: integratedcloudnative/
    tag: openness-21.03.06
