---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podsecurity
  namespace: kud
spec:
  interval: 5m
  chart:
    spec:
      chart: deploy/podsecurity
      sourceRef:
        kind: GitRepository
        name: icn
        namespace: flux-system
      interval: 1m
  values:
    roleRef: psp:privileged
