# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- set_fact:
    gopath: "{{ offline_path }}/golang_modules/cnca"
  when: offline_mode

- name: build CNCA plugin
  shell: source /etc/profile && GOPATH="{{ gopath }}" go build -o "{{ cnca_plugin_name }}"
  args:
    chdir: "{{ git_repo_dest }}/cnca/"

- name: install CNCA plugin
  shell: mv "{{ cnca_plugin_name }}" "{{ cnca_plugin_dest }}"
  args:
    chdir: "{{ git_repo_dest }}/cnca/"
