apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: flannel-vm
spec:
  config: '{
            "cniVersion": "0.3.1",
            "name" : "cni0",
            "plugins": [ {
              "type": "flannel",
              "cniVersion": "0.3.1",
              "masterplugin": true,
              "delegate": {
                  "isDefaultGateway": true
              }
            },
            {
              "type": "tuning"
            }]
          }'
