apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpa-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bpa-operator
  template:
    metadata:
      labels:
        name: bpa-operator
    spec:
      hostNetwork: true
      serviceAccountName: bpa-operator
      containers:
        - name: bpa-operator
          # Replace this with the built image name
          image: akraino.org/icn/bpa-operator:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: dhcp-shared
            mountPath: /var/lib/dhcp/
          - name: icn-cluster
            mountPath: /multi-cluster
          command:
          - /bpa-operator
          securityContext:
            privileged: true
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "bpa-operator"
      volumes:
      - name: dhcp-shared
        hostPath:
          path: /opt/icn/dhcp/
      - name: icn-cluster
        hostPath:
          path: /opt/kud/multi-cluster
