# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

sriov_cni: 
  url: "https://github.com/intel/sriov-cni"
  download_dir : "/temp/sriov_cni"
  commit: "2aa9b0e71e2d9eb53ac996005d32bd90c5f39d1d"

sriov_dev_plugin:
  url: "https://github.com/intel/sriov-network-device-plugin"
  download_dir: "/temp/sriov_dev_plugin"
  commit: "bf28fdc3e2d9dd2edcc4f0bceb58448ac9317696"

fpga_sriov_userspace:
  enabled: false
  patch_path: "{{ git_repo_dest }}/fpga/FPGA_SRIOV_USERSPACE_DEV_PLUGIN.patch"

# Config for nodes
fpga_userspace_vf:
  enabled: false
  vendor_id: "8086"
  vf_device_id: "0d90"
  pf_device_id: "0d8f"
  vf_number: "2"

# Config for master
config_map_path: "{{ git_repo_dest }}/sriov/configMap.yaml"
fpga_userspace_config_map_path: "{{ git_repo_dest }}/fpga/configMap.yaml"
