# SPDX-License-Identifier: Apache-2.0
# Copyright © 2019 Intel Corporation

---

- name: include common vars
  include_vars: ../common/defaults/main.yml

- name: create directory for certs used by AF and NEF
  file:
    name: "{{ certs_dest }}/ngc"
    state: directory

- name: copy genCerts.json file
  copy:
    src: "{{ git_repo_ngc_dir }}/scripts/genCerts.sh"
    dest: "{{ certs_dest }}/ngc"
    mode: a+x

- name: run script to generate cerificates
  shell: ./genCerts.sh -t DNS -n afservice -m nefservice
  args:
    chdir: "{{certs_dest}}/ngc"

- name: copy certs to remote nodes
  copy:
    src: "{{ certs_dest }}/ngc" 
    dest: "{{ certs_dest }}"
  delegate_to: "{{ controller_ip }}"

- name: build NEF component
  shell: source /etc/profile && make nef
  args:
    chdir: "{{ git_repo_ngc_dir }}"

- name: copy NEF binaries to build folder
  copy:
    src: "{{ git_repo_ngc_dist_dir }}/nef"
    dest: "{{ git_repo_ngc_build_dir }}/networkedge/nef"

- name: copy nef.json configuration file
  copy:
    src: "{{ git_repo_ngc_dir }}/configs/nef.json"
    dest: "{{ configs_dest }}/ngc"

- name: build NEF docker image
  docker_image:
    name: nef-image:1.0
    source: build
    build:
      path: "{{ git_repo_ngc_build_dir }}/networkedge/nef"
      pull: yes
      use_config_proxy: yes

