# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: fail if hostname is localhost
  fail:
    msg: "Hostname cannot be localhost (refer to how-to)"
  when: '"localhost" in ansible_hostname'

- name: check /etc/hosts for ipv4 hostname
  shell: grep -E "127\.0\.0\.1.*{{ ansible_hostname }}" /etc/hosts
  ignore_errors: yes
  register: grep_hosts_4
  failed_when: grep_hosts_4.rc == 1
  changed_when: False

- name: check /etc/hosts for ipv6 hostname
  shell: grep -E "::1.*{{ ansible_hostname }}" /etc/hosts
  ignore_errors: yes
  register: grep_hosts_6
  failed_when: grep_hosts_6.rc == 1
  changed_when: False

- name: fail if hostname missing in /etc/hosts
  fail:
    msg: "Hostname should be present in /etc/hosts for both ipv4 and ipv6. Refer to OpenNESS Experience Kits' how-to: section 'Setup static hostname'"
  when: grep_hosts_4.rc == 1 or grep_hosts_6.rc == 1
