# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: remove Go files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - /usr/local/go
  - /root/go

- name: remove exports from /etc/profile
  lineinfile:
    state: absent
    dest: /etc/profile
    line: "{{ item }}"
  with_items:
  - "export GOROOT=/usr/local/go"
  - "export GOPATH=~/go"
  - "export PATH=$GOPATH/bin:$GOROOT/bin:$PATH"
