# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: install libvirt
  yum:
    name: "{{ libvirt_packages }}"
    state: present
    skip_broken: yes

- name: enable and restart libvirtd service
  systemd:
    name: libvirtd
    state: restarted
    enabled: yes
    masked: no
