---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sriov-network-operator
  namespace: kud
spec:
  interval: 5m
  chart:
    spec:
      chart: deployment/sriov-network-operator
      sourceRef:
        kind: GitRepository
        name: k8snetworkplumbingwg
      interval: 1m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  values:
    operator:
      resourcePrefix: "intel.com"
