# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: copy git repository
  copy:
    src: "{{ git_repo_dest }}"
    dest: "{{ offline_path }}"
    remote_src: yes

- name: remove .git directory
  file:
    state: absent
    path: "{{ offline_path }}/{{ item }}/.git"
  with_items: 
    - "edgecontroller"
    - "edgenode"

- name: remove .gitignore
  file:
    state: absent
    path: "{{ offline_path }}/{{ item }}/.gitignore"
  with_items: 
    - "edgecontroller"
    - "edgenode"
