# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

#kubeovn_version: v0.8.0
kubeovn_version: v0.10.2
ovn_version: "2.11.4-1"

kubeovn_cleanup_url: "https://raw.githubusercontent.com/alauda/kube-ovn/v0.8.0/dist/images/cleanup.sh"
kubeovn_cleanup_dest: "/tmp/kubeovn-cleanup.sh"
kubeovn_cleanup_paths:
- /var/run/openvswitch
- /etc/origin/openvswitch/
- /etc/openvswitch
- /etc/cni/net.d/00-kube-ovn.conflist

kubeovn_yamls:
- "https://raw.githubusercontent.com/alauda/kube-ovn/{{ kubeovn_version }}/yamls/crd.yaml"
- "https://raw.githubusercontent.com/alauda/kube-ovn/{{ kubeovn_version }}/yamls/ovn.yaml"
- "https://raw.githubusercontent.com/alauda/kube-ovn/{{ kubeovn_version }}/yamls/kube-ovn.yaml"

openvswitch: "openvswitch-switch"
ovn-common: "ovn-common"
ovn-central: "ovn-central"
ovn-host: "ovn-host"

ovn_packages_apt: "unbound"

ovn_packages_to_remove: "openvswitch-switch,ovn-common,ovn-central,ovn-host,unbound"
