apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: capm3-system

resources:
- namespace.yaml
- ../base/default

configMapGenerator:
- envs:
  - ironic_bmo_configmap.env
  name: ironic-bmo-configmap
  behavior: merge

secretGenerator:
- literals:
  - password=7c21cf52ef163f5994ec
  name: mariadb-password
  type: Opaque
  behavior: replace

patchesStrategicMerge:
- data-volume-patch.yaml

images:
- name: quay.io/metal3-io/ironic
  newTag: capm3-v0.5.1
- name: quay.io/metal3-io/ironic-ipa-downloader
  digest: sha256:d2d871675b629bf66514ccda2e2616c50670f7fff9d95b983a216f3a7fdaa1aa
