apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: capm3-system

resources:
- namespace.yaml
- ../base/default

configMapGenerator:
- envs:
  - ironic_bmo_configmap.env
  name: ironic-bmo-configmap
  behavior: merge

secretGenerator:
- literals:
  - password=7c21cf52ef163f5994ec
  name: mariadb-password
  type: Opaque
  behavior: replace

patchesStrategicMerge:
- data-volume-patch.yaml
