# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: enable and restart kubelet
  systemd:
    name: kubelet
    daemon_reload: yes
    enabled: yes
    masked: no
    state: restarted
