apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: capm3-system

resources:
- ../icn

patchesJson6902:
- path: remove-dnsmasq-patch.json
  target:
    kind: Deployment
    name: capm3-ironic
