---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.roleRef }}-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.roleRef }}
subjects:
- kind: Group
  name: system:serviceaccounts:{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
