# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: detect path to GRUB config
  block:
  - set_fact:
      grub_file_path: /boot/grub2/grub.cfg

  - name: check if host is using EFI
    stat:
      path: /sys/firmware/efi
    register: efi_sys_dir

  - block:
    - debug:
        msg: "EFI detected"
    - set_fact:
        grub_file_path: "/boot/efi/EFI/centos/grub.cfg"
    when: efi_sys_dir.stat.exists and efi_sys_dir.stat.isdir == true

  - debug:
      msg: "grub.cfg file path set to: {{ grub_file_path }}"

- name: set GRUB_CMDLINE_LINUX_DEFAULT variable
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT=" {{ additional_grub_params }} {{ default_grub_params }}"'
    insertafter: EOF

- name: regenerate grub.cfg 
  shell: "grub2-mkconfig -o {{ grub_file_path }}" 

- name: check current kernel CMDLINE for required params
  shell: grep -q "{{ additional_grub_params }} {{ default_grub_params }}" /proc/cmdline
  register: cmdline_grep
  ignore_errors: yes

# Only applied together with os_kernelrt role
- name: Apply realtime tuned profile
  shell: tuned-adm profile realtime
  when: tuned_rt|default(False) == True

- name: reboot the machine to apply new kernel params
  reboot:
  when: cmdline_grep.rc == 1
