apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kud

resources:
- ../base
- issuer.yaml
- certificate.yaml

patchesStrategicMerge:
- delete-nodereport-daemonset-patch.yaml
- delete-init-pod-patch.yaml
- delete-discover-pod-patch.yaml
- delete-install-pod-patch.yaml
- delete-webhook-secret-patch.yaml
- daemonset-init-containers-patch.yaml
- webhook-server-config-patch.yaml
- webhook-config-inject-cert-patch.yaml

patchesJson6902:
- path: webhook-client-config-patch.json
  target:
    kind: MutatingWebhookConfiguration
    name: cmk-webhook-config

images:
- name: cmk
  newName: integratedcloudnative/cmk
  newTag: v1.4.1-no-taint
