---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: services
  namespace: emco
spec:
  interval: 5m
  chart:
    spec:
      chart: deployments/helm/emcoBase/emco-services
      sourceRef:
        kind: GitRepository
        name: emco
      interval: 1m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  dependsOn:
  - name: db
  values:
    global:
      repository: registry.gitlab.com/project-emco/core/emco-base/
      pullPolicy: IfNotPresent
      loglevel: warn
    orchestrator:
      imageTag: "22.03"
    ncm:
      imageTag: "22.03"
    rsync:
      imageTag: "22.03"
    clm:
      imageTag: "22.03"
    ovnaction:
      imageTag: "22.03"
    dcm:
      imageTag: "22.03"
    dtc:
      imageTag: "22.03"
    nps:
      imageTag: "22.03"
    sds:
      imageTag: "22.03"
    its:
      imageTag: "22.03"
    gac:
      imageTag: "22.03"
    sfc:
      imageTag: "22.03"
    sfcclient:
      imageTag: "22.03"
    hpa-ac:
      common:
        repository: registry.gitlab.com/project-emco/core/emco-base/
        imageTag: "22.03"
    hpa-plc:
      imageTag: "22.03"
    workflowmgr:
      imageTag: "22.03"
