apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: db
    namespace: emco
spec:
    interval: 5m
    chart:
        spec:
            chart: deployments/helm/emcoBase/emco-db
            sourceRef:
                kind: GitRepository
                name: emco
            interval: 1m
    timeout: 10m
    install:
        remediation:
            retries: -1
    upgrade:
        remediation:
            retries: -1
    dependsOn:
        - name: podsecurity
    values:
        global:
            pullPolicy: IfNotPresent
            db:
                rootPassword: ENC[AES256_GCM,data:cJlygh0lRSW35FfB90NP5w==,iv:KHvVw3U466bei8p5QuCZ7vQL4HmVRPX8fqKqnsjfYqY=,tag:PQaxEerT50TDext+17cw1w==,type:str]
                emcoPassword: ENC[AES256_GCM,data:Ze01GVul673hC3bQyFlWMg==,iv:izokFvy5cE8QGSOYOtloveWW/pvgcrU8z6FBF2EnTZA=,tag:jdqwGBt/HIGeCk3rop9WAQ==,type:str]
            contextdb:
                rootPassword: ENC[AES256_GCM,data:CmkuHNCVI3pTpSD2UfGqKg==,iv:0mAYVPcrzGHuqDtTRnB/aMmUAJUALzDvacdb/Csm/+U=,tag:vFH4ZieeHoI+4vPRvFEyNw==,type:str]
        etcd:
            clusterDomain: cluster.local
            persistence:
                mountPath: /mnt
        mongo:
            persistence:
                mountPath: /mnt
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-04T16:06:13Z"
    mac: ENC[AES256_GCM,data:RdleJnUnwjaLGh5Lji4QNzIWosZM/MZjBUCTXyNEn9rLKg1V32qEGXEnAkbZLkEpDVHePxvybfKNUUpCMLwfZmoBvdJvFJaaj0r7C0Ir929kjBR2w5h8VKax8qwoM1XjvcKWtjXt0VAyTVDb+GfCTh55ds1Btu8H5A1CaUEzre0=,iv:QTKDRzphXuRz2vEQ+rNncUdsx4YKO4Um3EbbPoOvDxI=,tag:oDEsB0IdL8Q2mMsiyd6fRA==,type:str]
    pgp:
        - created_at: "2022-05-04T16:06:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA4SX7nk+q+zPARAAWN/dhxmibhCAyVOUeyNtLMp2uuJkiiB6d5ymE0GAdWEk
            cIAZEUj0uxQBtKrjNDvrxVSeHi9ICIfclVbDrWvd3eGVSXccu+SthhDIstrVQu7D
            /jkYg6MCGvLHDXofCgu3/9KDLqi44xVVPUS7GTY7pee46MnSFskXY7XE1iBqDHdq
            ivc1sE7dIr60WADsuMGX2pLB4w2DQG+6bJ5Out3gJDgIH5ZTC2JcQGeuGLbh6BGY
            xoImV7GxUbGlHivxykaRojgMow0CpXdtz2YCg8RvrlhimspLFjw+XnLCLN5DZ5P+
            lYBwPxokz49nL157i0cVAcC0nQ1TrAtbPeoADz18Lbl5I5Fb8A33qBS/cIwWuJeO
            nP0VnJeJbEShmS2Ep+t/8Gv/TzeEnDnkpvO7dfWC+NSPVzbdnoZwFAtrBKOuCKeG
            xW993y80XLOzfWsFgzozTdrhIMG6Rl4UrGlzGoiSDCNeAZY6+SGsuQ+pn9spSsZB
            bYxG2Vdahzdak54IPmrqgRTohPiUHUU4rF7VM5H0uondSou9AT0YZf1DBgZ4H8x4
            mKTUMeNmD0SG3K8ut9rKwZvhUPmBkprtIAbKmebZLZ+tO5uopcy+qa4/HRO8Om/L
            5/ryDANFbyEwJ+D/jo/i2Rqu6nxZrfGrm5lkSnQiXjCTB1eYQ9XOF8cZqKvqFiHS
            5gFknP6G3S4oiFg64bu5K3Ww5Yuz4dOcG0mDcscGVsqd+U5oqqAxNu6nwfeSfVan
            W7ZC2Usj4os/U1DBbwEEXsDkA/AXnQmw+pbfxMsvkiZ3X+LzPXN9AA==
            =zzVM
            -----END PGP MESSAGE-----
          fp: A4B4A47A1DB07DE00E8158BE411E23534CA8FAE0
    encrypted_regex: ^(bmcPassword|ca-key.pem|decryptionSecret|hashedPassword|emcoPassword|rootPassword)$
    version: 3.7.1
