# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: create temporary custom .openness_gitconfig
  include_tasks: ../../../git_repo/tasks/gitconfig_bootstrap.yml

- name: Build CLIs
  block:
  - name: build and copy InterfaceService CLI
    block:
    - name: build interface service cli
      #shell: source /etc/profile && go build -o dist/interfaceservicecli ./cmd/interfaceservicecli
      shell: . /etc/profile && go build -o dist/interfaceservicecli ./cmd/interfaceservicecli
      args:
        chdir: "{{ git_repo_dest }}"
    - name: copy interface service cli
      copy:
        src: "{{ item }}"
        dest: /usr/local/bin
        remote_src: yes
        mode: '0755'
      with_items:
      - "{{ git_repo_dest }}/dist/interfaceservicecli"
      - "{{ git_repo_dest }}/kube-ovn/kubectl-interfaceservice"

  - name: build and copy EdgeDNS CLI
    block:
    - name: build EdgeDNS cli
      #shell: source /etc/profile && go build -o dist/edgednscli ./cmd/edgednscli
      shell: . /etc/profile && go build -o dist/edgednscli ./cmd/edgednscli
      args:
        chdir: "{{ git_repo_dest }}"
    - name: copy EdgeDNS cli
      copy:
        src: "{{ item }}"
        dest: /usr/local/bin
        remote_src: yes
        mode: '0755'
      with_items:
      - "{{ git_repo_dest }}/dist/edgednscli"
      - "{{ git_repo_dest }}/kube-ovn/kubectl-edgedns"

  always:
  - name: remove .openness_gitconfig
    include_tasks: ../../../git_repo/tasks/gitconfig_remove.yml
