# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: get worker node name
  block:
  - name: hostname
    command: hostname
    register: hostname_output
  - set_fact:
      k8s_worker_node_name: "{{ hostname_output.stdout | lower }}"

- name: remove openness definitions
  command: kubectl delete -f {{ item }}
  with_items: "{{ openness_yamls }}"
  ignore_errors: yes

- name: remove secrets (root CA and certgen)
  shell: kubectl delete secret {{ item }} --namespace=openness
  with_items:
  - certgen
  - root-ca
  ignore_errors: yes

- name: remove openness namespace
  shell: kubectl delete ns openness
  ignore_errors: yes

- name: remove generated files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "{{ certs_dest }}/client/interfaceservice"
  - "{{ certs_dest }}/client/edgeclient"
  - "{{ certs_dest }}/CA"
  - "{{ certs_dest }}"
  - "/etc/openness"

- name: remove kubectl plugins
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "/usr/local/bin/edgednscli"
  - "/usr/local/bin/kubectl-edgedns"
  - "/usr/local/bin/interfaceservicecli"
  - "/usr/local/bin/kubectl-interfaceservice"
