# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: check if docker is installed
  shell: command -v docker >/dev/null 2>&1
  register: docker_exec
  ignore_errors: yes

- name: prune everything
  shell: docker system prune --all --force
  when: docker_exec.rc == 0
  ignore_errors: yes
