# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: copy biosfw plugin to dir with executables
  copy:
    src: "{{ git_repo_dest }}/kube-ovn/kubectl-biosfw"
    dest: "{{ biosfw_plugin_dest }}"
    mode: 0755
    remote_src: yes
