# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: remove ovs/ovn related files
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ kubeovn_cleanup_paths }}"

- name: remove ovn packages
  yum:
    name: "{{ ovs_packages_to_remove }}"
    state: absent
