# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: check local syscfg_package.zip
  stat:
    path: "{{ syscfg_local_path }}"
  connection: local
  register: syscfg_local_file

- name: file not present
  debug:
    msg: "{{ syscfg_local_path }} does not exists, BIOSFW won't be set up on the node"
  when: syscfg_local_file.stat.exists == False

- name: set up biosfw for the node
  block:
  - name: copy local syscfg to remote
    copy:
      src: "{{ syscfg_local_path }}"
      dest: "{{ syscfg_remote_path }}"
  - name: build BIOSFW worker image
    shell: make build-docker-biosfw
    args:
      chdir: "{{ git_repo_dest }}"
  when: syscfg_local_file.stat.exists == True
