# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: create tmp folder
  file:
    path: "{{ offline_path_common }}/tmp"
    state: directory

- name: create offline archive
  archive:
    path:
    - "{{ offline_path }}"
    dest: "{{ offline_path_common }}/tmp/{{ offline_archive }}"
    format: gz
