apiVersion: v1
kind: Pod
metadata: 
  name: httpd
  namespace: default
spec: 
  volumes:
  - name: storage
    persistentVolumeClaim:
    # Name of the PVC created earlier
      claimName: minio-local-claim
  containers:
    - name: httpd
      image: haibinhu/httpd:latest
      ports:
      - containerPort: 80
        hostPort: 8080
      # Mount the volume into the pod
      volumeMounts:
      - name: storage # must match the volume name, above
        mountPath: "/storage"

