# SPDX-License-Identifier: Apache-2.0
# Copyright © 2019 Intel Corporation

---

- name: build NEF component
  shell: source /etc/profile && make nef 
  args:
    chdir: "{{ git_repo_ngc_dir }}"

- name: copy nef binaries to build folder
  copy:
    src: "{{ git_repo_ngc_dist_dir }}/nef"
    dest: "{{ git_repo_ngc_build_dir }}/networkedge/nef"

- name: copy nef.json configuration file
  copy:
    src: "{{ git_repo_ngc_dir }}/configs/nef.json"
    dest: "{{ configs_dest }}/ngc"

- name: build NEF docker image
  docker_image:
    name: nef-image:1.0
    source: build
    build:
      path: "{{ git_repo_ngc_build_dir }}/networkedge/nef"
      pull: yes
      use_config_proxy: yes

- name: deploy NEF
  shell: kubectl create -f {{ git_repo_ngc_dir }}/scripts/networkedge/ngctest/podNEF.yaml

