# SPDX-License-Identifier: Apache-2.0
# Copyright © 2019 Intel Corporation

---

- name: build AF component
  shell: source /etc/profile && make af
  args:
    chdir: "{{ git_repo_ngc_dir }}"

- name: copy AF binaries to build folder
  copy:
    src: "{{ git_repo_ngc_dist_dir }}/af"
    dest: "{{ git_repo_ngc_build_dir }}/networkedge/af"

- name: copy AF configuration file
  copy:
    src: "{{ git_repo_ngc_dir }}/configs/af.json"
    dest: "{{ configs_dest }}/ngc"

- name: update af config file
  shell: jq '.ServerConfig.Hostname="afservice" | .ServerConfig.UIEndpoint="http://{{ controller_ip }}:3020" | .CliConfig.NEFHostname="nefservice"' /etc/openness/configs/ngc/af.json | sponge /etc/openness/configs/ngc/af.json

- name: build AF docker image
  docker_image:
    name: af-image:1.0
    source: build
    build:
      path: "{{ git_repo_ngc_build_dir }}/networkedge/af"
      pull: yes
      use_config_proxy: yes

- name: deploy AF
  shell: kubectl create -f {{ git_repo_ngc_dir }}/scripts/networkedge/ngctest/podAF.yaml

