# SPDX-License-Identifier: Apache-2.0
# Copyright © 2019 Intel Corporation

---

- name: build OAM component
  shell: source /etc/profile && make oam
  args:
    chdir: "{{ git_repo_ngc_dir }}"

- name: copy oam binaries to build folder
  copy:
    src: "{{ git_repo_ngc_dist_dir }}/oam"
    dest: "{{ git_repo_ngc_build_dir }}/networkedge/oam"

- name: copy oam.json configuration file
  copy:
    src: "{{ git_repo_ngc_dir }}/configs/oam.json"
    dest: "{{ configs_dest }}/ngc"

- name: update af config file
  shell: jq '.UIEndpoint="http://{{ controller_ip }}:3020"' /etc/openness/configs/ngc/oam.json | sponge /etc/openness/configs/ngc/oam.json

- name: build OAM docker image
  docker_image:
    name: oam-image:1.0
    source: build
    build:
      path: "{{git_repo_ngc_build_dir}}/networkedge/oam"
      pull: yes
      use_config_proxy: yes

- name: deploy OAM
  shell: kubectl create -f {{ git_repo_ngc_dir }}/scripts/networkedge/ngctest/podOAM.yaml

