# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: check if host is edge node
  debug:
    msg: "HDDL is only for edge node host"
  when: "'edgenode_group' not in group_names"

- include_tasks: hddl.yml
  when: "'edgenode_group' in group_names"
