apiVersion: bpa.akraino.org/v1alpha1
kind: Provisioning
metadata:
  name: sample-kud-plugins
  labels:
    cluster: cluster-efg
    owner: c2
spec:
  masters:
    - master-1:
        mac-address: 00:e1:ba:ce:df:bd
  KUDPlugins:
    - onap4k8s
