# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

resources:
- cmk-namespace.yaml
- cmk-serviceaccount.yaml
- cmk-rbac-rules.yaml
- cmk-cluster-init-pod.yaml

patchesJson6902:
- target:
    version: v1
    kind: Pod
    name: cmk-cluster-init-pod
  path: rewrite_args.yml
