apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nfn-agent
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: nfn-agent
          volumeMounts:
            - mountPath: /var/run
              name: host-var-run
              mountPropagation: Bidirectional
