---
- project:
    name: icn-private
    project: icn
    project-name: icn
    nexus_log_subdir: intel/ICN_CI_logs
    stream:
      - master:
          branch: master
    jobs:
      - icn-stream-verify
