---
- project:
    name: icn-vagrant
    project: icn
    project-name: icn
    nexus_log_subdir: intel/ICN_CD_logs
    target:
      - verifier
      - verify_nestedk8s
    stream:
      - master:
          branch: master
    jobs:
      - icn-stream-vagrant-verify-target

- project:
    name: icn-bm
    project: icn
    project-name: icn
    nexus_log_subdir: intel/ICN_CD_logs
    target:
      - bm_verifer
      - bm_verify_nestedk8s
    stream:
      - master:
          branch: master
    jobs:
      - icn-stream-bm-verify-target

- project:
    name: icn-bluval
    project-name: validation
    project: validation
    group-id: org.akraino.validation
    refspec: refs/heads/master
    branch: master
    view:
      - project-view
    blueprint:
      - icn
    stream:
      - master:
          branch: '{stream}'
          gs-pathname: ''
          disabled: false
    validation_lab:
      - intel
    build-node: master
    jobs:
      - bluval-run-daily-tests
