# permissions for end users to view bmceventsubscriptions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bmceventsubscription-viewer-role
rules:
- apiGroups:
  - metal3.io
  resources:
  - bmceventsubscriptions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal3.io
  resources:
  - bmceventsubscriptions/status
  verbs:
  - get
