# permissions for end users to view firmwareschemas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: firmwareschema-viewer-role
rules:
- apiGroups:
  - metal3.io
  resources:
  - firmwareschemas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal3.io
  resources:
  - firmwareschemas/status
  verbs:
  - get
