# permissions for end users to edit hostfirmwaresettings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hostfirmwaresettings-editor-role
rules:
- apiGroups:
  - metal3.io
  resources:
  - hostfirmwaresettings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal3.io
  resources:
  - hostfirmwaresettings/status
  verbs:
  - get
