# permissions for end users to edit preprovisioningimages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: preprovisioningimage-editor-role
rules:
- apiGroups:
  - metal3.io
  resources:
  - preprovisioningimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal3.io
  resources:
  - preprovisioningimages/status
  verbs:
  - get
