# permissions for end users to view preprovisioningimages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: preprovisioningimage-viewer-role
rules:
- apiGroups:
  - metal3.io
  resources:
  - preprovisioningimages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal3.io
  resources:
  - preprovisioningimages/status
  verbs:
  - get
