# SPDX-License-Identifier: Apache-2.0
# Copyright © 2019 Intel Corporation

---

- name: check Docker service
  shell: systemctl status docker
  ignore_errors: yes 
  changed_when: false
  args:
    warn: false
  register: docker_service_status

- name: check Docker container NEF is running
  shell: docker ps -a | grep nef-container
  changed_when: false
  ignore_errors: yes
  register: docker_container_running
  when: docker_service_status.rc == 0

- name: remove NEF container
  shell: docker rm -f nef-container
  ignore_errors: yes
  register: docker_container_removed
  when:
    - docker_service_status.rc == 0
    - docker_container_running.stdout != ""

- name: remove NEF image 
  command: docker image rm -f nef-image:1.0
  ignore_errors: yes
  when:
    - docker_container_removed.rc == 0
    - docker_service_status.rc == 0
    - docker_container_running.stdout != ""

