kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-local-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
  storageClassName: local-storage

