apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: machine-4
spec:
    interval: 5m
    chart:
        spec:
            chart: deploy/machine
            sourceRef:
                kind: GitRepository
                name: icn
            interval: 1m
    values:
        machineName: machine-4
        bootMACAddress: 52:54:00:7a:b4:55
        bmcAddress: redfish-virtualmedia://192.168.121.1:8000/redfish/v1/Systems/41d41744-3dc6-453d-a498-dbd795c5d748
        bmcUsername: admin
        bmcPassword: ENC[AES256_GCM,data:X3RQuiAyJL8=,iv:n+nYSadsGLyCYlqXT2hN+XjSrfSMnEObgOyfzRZnfHc=,tag:A3/h/K3Rc48xFzqsDkD7Hw==,type:str]
        bmcDisableCertificateVerification: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-06T16:16:45Z"
    mac: ENC[AES256_GCM,data:0NGvFO9SN4W4aYys85584l5C39B1JcETmehsp88MEaR4qfoZCVGtdDDMFWWAdmbW9QM8WOsU+v7riAeD+W9V+E+YvWMRWuCQZu9VyHivbs4bDlYqM821KG2NFfyBmyDxRyTlbTDNOlqAPliGUAEKSCzyrrHHrE7MLgwhIhjAlS0=,iv:8XiGeofmQra0AxsD6fk1Z+2zfiwkSyU8f6naGpS1wMo=,tag:4b6Olt6A21wGaX5lD7lVOg==,type:str]
    pgp:
        - created_at: "2022-04-06T16:16:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA4SX7nk+q+zPARAAhG6H9zaTMRvR7IwA6sMO9ojp9QexlwsG/vea9x84jcb1
            XakBuqaOuq4w9KK59BjR6lMmam8uhQDKfsgin8N+mA7WU8l1Dp0CQF+2LYH6ODFD
            Oc4J9BlKDPdDFhe7Uyy6nflV2qQrxRRXAlOEXCHvVJweIsttmdNFTtRZLX6ZZs6U
            /42/0sHJUACyKEM5tJoZyXxxHdrqSmoVrZpZSTRBus4DmBfF4bL485FgV9MoT3VM
            3EQoUm3nDm1KI5Ic9f6aBVsBA3c/lH7q0+waQhzJ7TrtBJ/JEggQ0YDN76xOeZip
            VusFOORGmqxfBcx4RZQWObcvyDM7AwUzZwDdhU/RKa/Rm/WN34WEqUEdbvBlyPx5
            Dqt0zw2ZgSMpPCY/8Ezve1HUlavGaF38XGDqwX8pmou17/TIYHLtTqBdx1s+c3Hr
            Qcb6bnbU1ssABP5gopYV6ERE6lYAsCSqQ9qSruuocq0pSlJVaTD1hxRqSNM7BTnp
            uM22YA99hKpPaBS9eIhYRtORK57QZBCMYgDEtOau8t8Oa6ZTvsaHlIL+gKPtiNsm
            uuOGClNByMgQw6QuNFikcfdWQhz4ebrmX81E+qnwiMMuHNsv9K4UO8GaeGofOBlH
            as4hrG29AlNCqD3hciSrfRvw7JW0pS1itW4YpY5ikDsV0QR//Nij0Anool7A4PbS
            5gFv2tbChBdpxY/IQekeYh6+COqojps/vk+56TuQarRYsQgqW0rkvjEZt4DQigJt
            sYTDCk5kL3tlas4xte/fq2bk0DKrZ5LAC0yzZSjqNM2kPOLe6mtgAA==
            =m3Fa
            -----END PGP MESSAGE-----
          fp: A4B4A47A1DB07DE00E8158BE411E23534CA8FAE0
    encrypted_regex: ^(bmcPassword|ca-key.pem|decryptionSecret|hashedPassword|emcoPassword|rootPassword)$
    version: 3.7.1
