apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: machine-3
spec:
    interval: 5m
    chart:
        spec:
            chart: deploy/machine
            sourceRef:
                kind: GitRepository
                name: icn
            interval: 1m
    values:
        machineName: machine-3
        bootMACAddress: 52:54:00:50:63:44
        bmcAddress: redfish-virtualmedia://192.168.151.1:8000/redfish/v1/Systems/ac3527cc-1223-4794-a0a8-3f6a12f69f17
        bmcUsername: admin
        bmcPassword: ENC[AES256_GCM,data:d7elM5OFdNU=,iv:FFlJteQi0o/nRIGY8dDp+/GhTVoMjns1jeeAQpyLD60=,tag:JnAVonB74y+q1GGYFqyrWA==,type:str]
        bmcDisableCertificateVerification: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-17T16:33:24Z"
    mac: ENC[AES256_GCM,data:bWoYd6AZ+fkSoUJchUDwDFkIh1ltlYRZewNG56swZrO2jgjT7DOG5WtXjTSbbY5Hqk/6liMA2cIQoKZBvUdOV3v0ZIr+B4F85NZlvYwweoLCyvDM6ndbtTdcgbvG6L6HidvYOgqav73dTImJwdD57FquUeP6z21G6KWc7msTRUI=,iv:qW0FZmDgtZZLAvOtEhGnwcG60v27nXaiJ6dKsoxdrGE=,tag:GdSmtVG8+7geIcNMc3+vzQ==,type:str]
    pgp:
        - created_at: "2022-03-17T16:33:23Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4SX7nk+q+zPAQ//ZbmxHC8O1plZ0XA7lTNoViBNc9uBRA1IKi5SBjj/rq9R
            7mi2uChDgGLP9SxZqxZxMvyF9n3eQQhl9J9fqnrGsAZGc7BstI7zvA0c26B5YP3S
            IMXxJBsvpeD1vw6MQKPjZNSay1zTUXQsWfy2JafHmASgKvFTxGIcKSDInKgDTJ8d
            40NnL3OGp97lN3gM2WG5mA8tvRWX0ScXiOoa55AfeUjHlsoKnV+bvtl4W0Gc9WFw
            1ehiq+bqJmPUPgb22UwCocfuxWS67BwiTEv9E/GRhPmRCLTGAHWgtEXjmPAjXM0v
            o9cy2bjannWIWJGI0wOxWEjB0s9z2bEcINmxw32G2rgHl6RFVGlcWEM8HdpJYL3O
            xyoeKQq0ScrYU27dMdstB2k9psnavOVGt8V4Y6La6AO9urVEXLWL1ODTE7rjE1+8
            GNgGmu732Xm/K12WadvCJCqx9TfW2XOxAGhrRawe6pKuczVVSjmiL4fniaDI34zS
            sEOE/2F5EH7QKsDYQhHL5IDtF833MWh9hs2s78P8oRriJrU4XzJF43cOFECZy00f
            J2fsUt4EE1feuT5FG8Ym2lj/7IukGy1hNUWTHcKfgwJW7j+/YRUPigVO8GfqJpdQ
            tKxUqS7V034FGB98cgwa0r/Fr6YVuW0u0Frt+0LqP2xu75xFOiftpSiRuD/PqYfS
            XgEhGSAqoGPNxc7uUWMvorCo86G4lP+0JiVZQVNhEu6hQHs96YIE2mg7ry51cC5a
            4/vK/GUkyejV2GqNnBaw6ZlJ1j2/u0eV1eXF1iwaxTWXm9zq/3d4p1JrV39KfB4=
            =Aabd
            -----END PGP MESSAGE-----
          fp: A4B4A47A1DB07DE00E8158BE411E23534CA8FAE0
    encrypted_regex: ^(bmcPassword|ca-key.pem|decryptionSecret|hashedPassword|emcoPassword|rootPassword)$
    version: 3.7.1
