apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: machine-3
spec:
    interval: 5m
    chart:
        spec:
            chart: deploy/machine
            sourceRef:
                kind: GitRepository
                name: icn
            interval: 1m
    values:
        machineName: machine-3
        bootMACAddress: 52:54:00:50:63:44
        bmcAddress: redfish-virtualmedia://192.168.151.1:8000/redfish/v1/Systems/ac3527cc-1223-4794-a0a8-3f6a12f69f17
        bmcUsername: admin
        bmcPassword: ENC[AES256_GCM,data:9JZ/HUTUWJI=,iv:KslJQTeyR+x5/bVgVxed7qNA5/1UovPp+7d8h7Mc09E=,tag:QM/i/HD0C14xl7NQ1P5tig==,type:str]
        bmcDisableCertificateVerification: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-08T22:18:32Z"
    mac: ENC[AES256_GCM,data:oHwb3xE1OoJZ1FSD0BXPO8IKEipZGtpF9+5yTTylUu2d+pkji8Ry0lZAkikba7yq6qbfDzulsDZOV22NmU3PxObapYiCLsIJsSr1kGkZ/IqVNJ0y3D17l4CoYOITv/NWzJ+WugWRnfLSOeKjz+Cw+pewGeH2yzdaTTgOb5cApUM=,iv:fdiJ2egVMrzPbf6zqKG0UQArbrUELVasWpjtK2K4Nfw=,tag:VSEho86MN3jzFT9l2Vtr4A==,type:str]
    pgp:
        - created_at: "2022-03-08T22:18:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4SX7nk+q+zPAQ//TzmCFJcf+lxl5cqj/jJadRPB+OyEdq+LeNZuZWW+RoY5
            c4Al/8hBzzEuA3KEIT/0KoG/g9Klbb3kbrLBzgZys0+bnKYrCWM1vPoBoHDNuLwP
            Yy6AemctduHi1S0HolaWE/4uxxHjADsnCOAII6wJRx3/sve1c3mjnIzki8xlRMGK
            3n4nZA+4emZhIcTQtOLfgDaR0cQlwQ7/pV67GpYV3h3dvXkqiWF62WwXE7XmmKNM
            jV0UOhG5eTuRvwEJYJ1LIIDUwvrJrx578uFDFUNEN19d3ORVHVL0VA9+sPFw+u41
            v5MF6EbUwoJQtF2GbAJeSGMsDFBXoIbrdKe3UejJ4+1d/x0dPCom0QDg3uu5EPaH
            BUU7KXma2ACch0ZLjW7CkAO3FHnUrvcyE2P3/kx+zSSFr3HmbUPuByXjZs537dNq
            eVXQPAldoPfHMxS/usxjYzbvOJoCheQGzB6dP2Nk+fPaNSW19g2sUlBmRjBL3XT3
            A8h+HGqiPNnW3Pr/cGb44G6EJfktg6CqVNBPn+aylG/h+EcnWqF/fqfcIiztfDuf
            BX2X+8e1pEKaHwRcdqlqjbN9mDETvtQsigYSMZ9xnW0SCZdgMSlowPfwrJ6cxfBD
            bLQHsrXMX3Ffqc7dOkUdWJ0z12Pdo+GtigkwYspmP1J80l7KQE0nmBjfrjnHCazS
            XgGTKMAVEJx0+VVaTqd1tCP8eRri6fnvadI4KfOqHeknQdjoRspus9j8D4hwLux/
            Gay2E1zpOKw84SJm9S1R9vqlwgTknjKrlZHtnCaL8/nP1YS5vXP1LUPaRcYQGf8=
            =pWpn
            -----END PGP MESSAGE-----
          fp: A4B4A47A1DB07DE00E8158BE411E23534CA8FAE0
    encrypted_regex: ^(bmcPassword|ca-key.pem|decryptionSecret|hashedPassword|emcoPassword|rootPassword)$
    version: 3.7.1
