apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: machine-1
spec:
    interval: 5m
    chart:
        spec:
            chart: deploy/machine
            sourceRef:
                kind: GitRepository
                name: icn
            interval: 1m
    values:
        machineName: machine-1
        bootMACAddress: 52:54:00:c6:75:40
        bmcAddress: redfish-virtualmedia://192.168.151.1:8000/redfish/v1/Systems/ab389bad-2f4a-4eba-b49e-0d649ff3d237
        bmcUsername: admin
        bmcPassword: ENC[AES256_GCM,data:yRbB7naw81M=,iv:5cOPLhjsGV4IHCqpj9v719FzlaWyu0ovp61jXTGbb3k=,tag:Qus/zWzJATkvyowuJ5c1/w==,type:str]
        bmcDisableCertificateVerification: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-08T22:12:10Z"
    mac: ENC[AES256_GCM,data:BeoMxcdZXRw/ZTOaPDFhuLp57Dqa2DkX438ge1+pqUTXbztyNwgZgU/A9iOThChLeLros4ba+YR+L2v+7+3KsNvOzGWoxODHH1/3lamO3SlBGuOr4IrOC3If7KHV0zgI0puYJlYDIo75CPCfl22GGkPc1onGr+KNy3o3WH8EcNw=,iv:y5X0hEm7DgwOzIHN2Z4mDYBZ3mmesvejXV3fcRkSmlQ=,tag:YxLBZAs+KnQ2G4OAEPa3Pw==,type:str]
    pgp:
        - created_at: "2022-03-08T22:12:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4SX7nk+q+zPAQ//bx9JBswCG+kGJLCr3apqCKelAj2BQac3flWRJP0nwnq5
            Ouv9gq+7044aRwUo0r9CYwetIxRr/h5kgusaeKcv+6DPSXvXn4AfZZUBULmvGoJy
            qI5D7h5x3hiylfP9I1z8ToHjf+0CtAWgVdlmOwTwWnBJXRscfmPWiPkAgswGkM/5
            eTteuIpar4du6kc1T+heiZ71spgkEt912/KYo4KR5eetGuVFm4iEyV0ZYRFcXzML
            IQTtS8SHmpoYGRC3a1foZoulOU0uhmMJuesCgIGNOvXtIvvIDbUXaO3BoKAjG+OT
            Jf2eFw5BykCPKgeF6AkG/6WVgn/xBFfwpz/6IG+xFwKfIxXnyR7p2tqxT43tcJwC
            p9OLBwK8txvfTV1Q2qf5xB3+o/o6AXmX3F4Cl9gdurmGyL844Q9gGWp9DP+gP+ms
            dbA0tLYpbrw/GH0UFykSM7u7pZYgX68vvM5pcCDpdqrDdPJHXBGuhUB9JX9jNX0C
            gossAJ9BqQSFDx3y+S2T6wnQQN7+Xvqnn07q52GJb0VJhHT+JJHrlvmBHBCAJOqe
            jRq6HeIH/UU7Tf/zcY8YcTVadWPxPoVmHl0oxMc3Jaw01atlT3tPmcAGqfY6xin4
            4GGcLbSACr9R6moggaBg2JcJba1h5XNj7l5pl4hSKQtBn2Nz7uBiHs/0AF9zflHS
            XgFsEXOiUDzDJsXUUaC8SiwIFq4cTqMToPKzADYyIZbFXxQn1FRfrpwErT/MPldl
            5OjmJ1dx43qGv2rmyneA53cuqR9jonMp5Rbw+uaVaAulixPrPkQqbca73u8K+wk=
            =R2Ib
            -----END PGP MESSAGE-----
          fp: A4B4A47A1DB07DE00E8158BE411E23534CA8FAE0
    encrypted_regex: ^(bmcPassword|ca-key.pem|decryptionSecret|hashedPassword|emcoPassword|rootPassword)$
    version: 3.7.1
