apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: machine-4
spec:
    interval: 5m
    chart:
        spec:
            chart: deploy/machine
            sourceRef:
                kind: GitRepository
                name: icn
            interval: 1m
    values:
        machineName: machine-4
        bootMACAddress: 52:54:00:7a:b4:55
        bmcAddress: redfish-virtualmedia://192.168.151.1:8000/redfish/v1/Systems/41d41744-3dc6-453d-a498-dbd795c5d748
        bmcUsername: admin
        bmcPassword: ENC[AES256_GCM,data:uw2VaC1/430=,iv:37Hbbykdb9y9iPwmbhDozXZZgZNYSff/pq7kLJ8bVN8=,tag:8XzqOCIgfTysZiQbCWA6hw==,type:str]
        bmcDisableCertificateVerification: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-08T22:18:33Z"
    mac: ENC[AES256_GCM,data:D0W2kA04mPzzmxIJ6PiYiSCufSObkkTMHo0QFZ7B6lmr7sDlj6/hfUq+m9wgXpJI5NzYkbOEmamT7y7kP4KXFullZZ9JdMB2tA9xcmb/wxy4DKZDPd9Cp9b7Qntmd12RE1F6GsZ2RsD+e5FKrG4vbCWnvEGXgpgHiRzHb5omLH8=,iv:a1kAWasbpiRnbbacjQKzpJ8N0MnfOdeRQ4oVJM+wbXc=,tag:lzFXz063lZ/o+BPwf8sv0Q==,type:str]
    pgp:
        - created_at: "2022-03-08T22:18:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4SX7nk+q+zPAQ/+PpNiHJ47H7WI2IsBaCR6+McpbM+V5jz/2WLiMm1JuIBw
            xMgcAwdHgzO9MikVCytjDslylZ20kyYSH0jCmeCzGuB7rrhEfIVx0dnyfHk3VyNj
            ZeubdqN5l8bXLWQnVJZYGMKERFdM1zGg0KVwulNLdE40eghUT0uRKPRLJ6iXzjZm
            olTK7/kTTqBQOpqkPxvkA/Q/G0zNiGp9JCMOqEfqrodgZk1QXY7qT7yKDVGs0I5V
            s1BftWCl/zH2QB0/FZ5YTMSUjXlCQJMuUWtRi2UA4hS6//S5PBF0jRhWaZVthgua
            cEJLJ1BDQikOUnH9POipIXsyBl0rVV1wzepZqMLPLWD00EEG2IxDNN3e7lcWjadk
            j1s6nnLbiIe9xmmIJUhCYcjkEVgu65J1I6g9bj8z2qYakzIEmnIJBmXgq/ayKEps
            CTEW9w5FMgZsiSZGYA64q2OZAjxi8q2ERL16cRXcEm+WCPefTuWZhmhlQEFFk34m
            V3tNMfhQ/6ZLB15u2Iw3ZtYl+XVtSeZuUBH+cu1m9uBAy6MIqtjZL+hkgHuGOTzn
            eJS9NoOmzk0/03eOZqFWZ0Q87lAyTZLwFCJbjVVqUriJb9f/6hBp1cQ5ywK5ks8F
            KF581j5XRljLW42wAaxYbuOHz0S7t3E1E4TiiFeydHWd0sjDwh0b4r7GK/JjVF3S
            XgGMHs94d8VCn4XQ+nbGdcsbRr7NMObqiMbkKStp2L4u0ll1QVM6o1kIoYGlD9pt
            PZPpHuewl/KuWHNio1LzEEI/oCUXGYRz6Apa1RbC93mBEqF116b5w5fOyYgwf/g=
            =A2dl
            -----END PGP MESSAGE-----
          fp: A4B4A47A1DB07DE00E8158BE411E23534CA8FAE0
    encrypted_regex: ^(bmcPassword|ca-key.pem|decryptionSecret|hashedPassword|emcoPassword|rootPassword)$
    version: 3.7.1
