apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: machine-2
spec:
    interval: 5m
    chart:
        spec:
            chart: deploy/machine
            sourceRef:
                kind: GitRepository
                name: icn
            interval: 1m
    values:
        machineName: machine-2
        bootMACAddress: 52:54:00:6f:d6:97
        bmcAddress: redfish-virtualmedia://192.168.151.1:8000/redfish/v1/Systems/8d747997-dcd1-42ca-9e25-b3eedbe326aa
        bmcUsername: admin
        bmcPassword: ENC[AES256_GCM,data:MXjNiK/VLHk=,iv:kYrdiu4+jYYfO+iLIjQpI3ClCbtPuOPLmNeVIEVvgyA=,tag:C4lHMJLO6RAvOgnuSPKl0A==,type:str]
        bmcDisableCertificateVerification: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-08T22:18:32Z"
    mac: ENC[AES256_GCM,data:ZCEilY76b2RSniStAdGQWAsU0AWVHUhGcN2Ki0C+gBkC4YRTT6pAyV04US6UuyPuXf8qZ5EkbUNYydRwBMuBwf6n+c4eaCrTc1IdmxlrWppg2mudIUC42BXU1yZ4nOyEkNlIchlHVdvzeuR/jyThXTuKHrE8wYe656GdgfvC0hE=,iv:KpMe0BIqMMVd/RZnOv+OpEf20xYkQDdby39pblmlw+0=,tag:hAcFMZSVffO03QTFklrsow==,type:str]
    pgp:
        - created_at: "2022-03-08T22:18:31Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4SX7nk+q+zPAQ//T01JKQPn71e5p7iKkQdofqa+o8qAuELrMjPGQVNJocMX
            ZQGsaNtyBiVIUL2NM3uYuQ7XCgDWMYjMm9pXj2fmxa0XAu8q3rOLdBdubqoUdaNn
            WpIRKPWVXfbwvwLaecthfLtGI//BF0avRK6HOfAy5mjLQ9TQOpUWUKnTaNDjpWGy
            egtO2qae4Fma+s+LG/w0hs2ktjCBRcAr9uiFttaxgp5SGw0HKN5L/Ks+6I0ON94s
            Bf7c9qFJjV/3/VeWcEpOIfcKjRGY+oFhwMmSKSLM7v2ocAz1RmvLgVw+uAhW6LBE
            Hlp+dz4wX5v9dYiC8K5A+sJgY5ONwJbUh6UKBaLofK8Yk3zZtP/5fz6+HYlAeXvF
            weIJ/oB2whu7OBabp0EKjBs4Z0ibh4pn49r/MwLSvAv0JCuSpZoYed+KhJPh2LAV
            cKyUSBKeRMfPxHhcQb3vWizbKriGxBQmy5dCtvDuT9SMFUuKspw8hzJanHGciRFq
            +ORgMfBp3uW+3TGFys1B7BYYU2/Vx0jy1X9Thn+druBGMHoRgVguqPIGqa7bNFXP
            nS6ZpbgaDxuReIMHGfohaULsAQshTjWAgp9cKXczW6Mda1gEmopQZ4d1Qee8vZPn
            +g84Qutggix2lFFC2UhgIc+s5Kptw/QXDC0WFsxoG9VMAXkywe0rROnww3Ji6ZPS
            XAFlYMlHKeNA6hDEVDFdN1q9C6mrqa4NZ/LdWkRd2f+3rZV1WOduh2Ea3fSrHwfK
            /h3Iky3SmO0GtdHtfvoDOTlof+ALVmypXKJtdnqwKD3wO7y6aEtKXyc7mius
            =o1ag
            -----END PGP MESSAGE-----
          fp: A4B4A47A1DB07DE00E8158BE411E23534CA8FAE0
    encrypted_regex: ^(bmcPassword|ca-key.pem|decryptionSecret|hashedPassword|emcoPassword|rootPassword)$
    version: 3.7.1
