apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: machine-3
spec:
    interval: 5m
    chart:
        spec:
            chart: deploy/machine
            sourceRef:
                kind: GitRepository
                name: icn
            interval: 1m
    values:
        machineName: machine-3
        bootMACAddress: 52:54:00:50:63:44
        bmcAddress: redfish-virtualmedia://192.168.151.1:8000/redfish/v1/Systems/ac3527cc-1223-4794-a0a8-3f6a12f69f17
        bmcUsername: admin
        bmcPassword: ENC[AES256_GCM,data:iu8UfIMCk/U=,iv:D8JCq6AnQJvxhEfj1rSp9Vwf0PEVi+tY1/KjCZmj7Z8=,tag:2QE9yMFva9uBMpjKqJohUw==,type:str]
        bmcDisableCertificateVerification: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-08T22:12:12Z"
    mac: ENC[AES256_GCM,data:EUIp20z8qa3GHfX2ffwowL2clqtFrqnU2fMC2DXNn8BgVUd3QAyT8WStkDJt2Qp0Jl3rMV/sEv8wzu+27lCycnnkZBlVMvQqOZN2Jg3i8iBOag18CHdyUcBrF2kqGt00Gc3i62u5SRnWwGwOr8oHPY+K9aLTvY8UE/F1GLuCrV0=,iv:CpYvPun+pgENL7x7O54uahs/BxD5IZ1dr/rl0zL93BM=,tag:+M4vjVGCGZpsrJ+rOE/XXQ==,type:str]
    pgp:
        - created_at: "2022-03-08T22:12:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4SX7nk+q+zPAQ//SjtkApKZtRD21/hW4eW8y7gAy6fmO0s7evmneXbVpc7d
            lijHAov4ZFOrlNlJwu6JFPSuw0Fw4l+zppLZlX9vm6AQm7Tt6e8YSF66KYVZUtax
            8/oRnBs8p5NMRXLdBDy2lglrFRY6Xdu0FcHOFXeNTdqdQ6rkzY6vNlJiv8zbrs6d
            9ICl67twXCyrwgDbttxNULx/A7GdG39uOIIQ56QOqUWuFo4uL6SGUWZbWfQ8jIrM
            +EeSDTmuu8eMhtUS0ep3f5ag5eiS197jo4eIUAx9B0hFGckAKEg2Gdp69qEYt4Qh
            xnlgw8CdRS2swI9tteJx786ALC8QszfTxJkKTxcjniDqUoAOP0iDuSSgaVbW9a7I
            5FwgZ5Dbn2dMgjqd5FlaZOuWzsDIWq7HMhfCq0xpo9fhS6Oo8dIyLk8dlpqmB/qN
            82j1DTuLEjHw5wdYdS0BJu67GK+2mJrBHsqhUhRs9HdE21/PPB1Iu4XWjNBiGLpK
            /IaMtW2ZATCIzz9oFBae4EWDnPLWou8pHMSGWWZYA51bSOi8nw4nZYT0rwKtIpsx
            Xfo72REY9qMk5D2/XrcgQBK66kiX0nTy60xclTkWM1N8di44Z8Uoory9AVVb/usR
            ET8ScDCx9WoVacYr66XnyTlzW9HPY3PsvS4F6RqWOK05rAA1MN6ZhtbvPOYNpwrS
            XgEfJX+9Jj+mVFFR/a4b8NQAGOUjditKOUmXIAv+lVrS+LGfQaeDD3DFXuzID8pg
            xfafiLNg1vjWd/2UoCKWYKo9RnMcGLi5ZFGPFZpCGjB9t6Ewd2CsZe9izavbs4Y=
            =osqQ
            -----END PGP MESSAGE-----
          fp: A4B4A47A1DB07DE00E8158BE411E23534CA8FAE0
    encrypted_regex: ^(bmcPassword|ca-key.pem|decryptionSecret|hashedPassword|emcoPassword|rootPassword)$
    version: 3.7.1
