apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: machine-2
spec:
    interval: 5m
    chart:
        spec:
            chart: deploy/machine
            sourceRef:
                kind: GitRepository
                name: icn
            interval: 1m
    values:
        machineName: machine-2
        bootMACAddress: 52:54:00:6f:d6:97
        bmcAddress: redfish-virtualmedia://192.168.151.1:8000/redfish/v1/Systems/8d747997-dcd1-42ca-9e25-b3eedbe326aa
        bmcUsername: admin
        bmcPassword: ENC[AES256_GCM,data:rPU4i3szc54=,iv:ClTYkNnleMHYkz80VDJVpyUrYkDJNvE6jF+FGlNTHhQ=,tag:ugyNLowV5N1vpCXdVOwKnQ==,type:str]
        bmcDisableCertificateVerification: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-17T16:33:23Z"
    mac: ENC[AES256_GCM,data:s3zt+Kn8lnAg0STA1+S67+1HhgYBWA+73c1xcyzhy9cvGHOMwdtgeGOSlOn6AA8WhBziH1d9aeWFHgYt8Ier1NmuuWIfGs8SIk3dAE1DLeAbmTwS884gRqgdvCa8Wl9h5cwET7boabGArhFmBjR9pTIzVulxbhvLaEara80NKEw=,iv:5y0D/KiL8yx62SQooGwkL9GEE9QgrJxTgwGsZfxTRk8=,tag:UStLQTg7WMwYoThXWyRVug==,type:str]
    pgp:
        - created_at: "2022-03-17T16:33:22Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4SX7nk+q+zPAQ//ewal2ez8J0ik39zFp4/zOgw0DR1QOPRTas1iLzQwOYd9
            j1/IkePpJcGPA8/VY28hR5bIbb/BDtssxFZRPHlhGFWiM34FVtTVFgE6U5g7Qnr3
            smFl6xTCaoO7NOQIBm3TZgzzOzmAmpYnSz1y58MNBxXa3sGaj16Yxhph2Akx3QOO
            PDU2RHcRQa3h/AMLtVkqkELBJ0S58jcbqMIagqdg3JF4fuynRvbB0WbvrO9MJGzK
            wIks4p2TKDc2q9GsyqGTv80xgHQLa9wI4Ygf+D9KM3sqDvpJhvqsa7LU/LboxAAU
            Ojoz/hjMY4pZgZTW7iVdj+CaBKKeU19ofgKdUvZBrvmIk5phK2P3RPRWNDhw/9TA
            McGE9rDpg+KNi/uVSJPeui26CUg/ISdHGLvxkM88JXA3kdcZMvKtOxOMoe8yaGak
            5m3hROSfAcci7qqQuEnj+FRbeMfef1EfcKFeUbRgPVuHNu2FlW1MRfdMG0EmGlfV
            FLqRUUg4yV3tBfYL/maETAUe9YiQ1qU6UOTF6Rl5sTiGYR335NoxQG1C5bmd5AMa
            JL4fsK6PZS0ZlQhBXXQrENeOFVLPTlQu4xP+mU2o+REO+NKj3xT/o51GaqjF1lUO
            Dy3csg9lyl5mf9itBdBFPpD1+9HGRoxbiph0lxJlMiq9a1hEltzBrENiZ8RGWrTS
            XgHoJyo4obXd4zy0v8K04pIDzZbxV5gFyAE95V7uOgrGcOQ0kxgqt1nflx4ROsJh
            J+227QI15gzZY+AFDvIMoEnAprmEAA9qWb/vTa+0Sg7C6yYWk6WymxpAejaWL1U=
            =d7hA
            -----END PGP MESSAGE-----
          fp: A4B4A47A1DB07DE00E8158BE411E23534CA8FAE0
    encrypted_regex: ^(bmcPassword|ca-key.pem|decryptionSecret|hashedPassword|emcoPassword|rootPassword)$
    version: 3.7.1
