apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: machine-1
spec:
    interval: 5m
    chart:
        spec:
            chart: deploy/machine
            sourceRef:
                kind: GitRepository
                name: icn
            interval: 1m
    values:
        machineName: machine-1
        bootMACAddress: 52:54:00:c6:75:40
        bmcAddress: redfish-virtualmedia://192.168.121.1:8000/redfish/v1/Systems/ab389bad-2f4a-4eba-b49e-0d649ff3d237
        bmcUsername: admin
        bmcPassword: ENC[AES256_GCM,data:wGDJehd9vZ8=,iv:Da50Xq2S+u2H7oyQ0k9SjDVNMmBXAGkGKceo5n+ZD4o=,tag:w+5758jtEMlWkaoV4QPssw==,type:str]
        bmcDisableCertificateVerification: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-06T16:16:38Z"
    mac: ENC[AES256_GCM,data:ijc0RpIqF9Dw9x2XKOZkC6odVIUlbyQhFj4xhi9ijBtQmh1nHsiXCHOpwRAxUXuk/Bc+quHw8DPuEz1QMxswR72hD00TPgE5cBrK8u2LkA4mVZEQRPp5tY8UTrxx04A2AyYGHU4LsRzkiQQUZgU2nkP3QhEy9V1jxIX09LzDu4I=,iv:O4Uyda15TV7ztqpOXDdVujZxg67ATF1eMQaKT8rqnTE=,tag:J4oKVFnHPDG+NXpcb8kyGQ==,type:str]
    pgp:
        - created_at: "2022-04-06T16:16:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA4SX7nk+q+zPARAAbFLFzb7DF8k18wZf1u7fnZ8jKdZyw5usV6LqHNTRSMqA
            spaSibYikrA8qYHkCCd3jmXjhopvI57uyffJYi2sKApyV5GqN4M0X70dCkCznqfJ
            p90SOZBfGKHgE9bSo67Coye1MqFsciZi4etqX5MUoLor67ChzvPrtKNYeFqrG1UJ
            /o3X7BQYM/I6AVlA6ZnXCeGDjwJnWbr2EJGrgbM28zm44Cp9ZHzNJ7+rxIjpFn6I
            bZYFJF0VbaKu5bsN/mIE5IKYGIM0ew4jlrcYMMG3rernwutfo5FF7hm8RswD5BLz
            V/uS6rpzwQFS0XeDjZnCFxWPOJbUeVaJ5HaeaR/fH7QBB5kBoi4wkJMsT8Hy/Otm
            5SwnKrDERxrI0n1GTPD710BDJcOlugo4GgA8ZGiz4Me3uIP5VKWvLOmXmFiJeBst
            L44nkE0I2RnAf3qIlA8SPC+SVhs7fBcxhjbJ3sDbHMSsHPsdioio+yAkr4XT8+A0
            x9OKG+RJjr7wTXJ3+mjKg0c825J7r7U4ZauqcoI/J2o3D0CRLPbVV6/Xtb6S8ZTc
            anlnltQY9th1jP9Ysig3Pu83YnskEzmJyL4MQ/yZciv5gjNvbQr/ElM7SSK2LPGU
            37FH7lCkSfJ1p4+Yuo3kXg9dwScGhvDHMPJCtowZQ3ollDPnFo9htp6WShFX14bS
            5gGd5YuQ7RyUfNfe3orMhuCu9mCtl4b+bdAtj/2tz2O1S5NQTa9vPOwxR7mZmspJ
            V+zRhgHC/r8oPvZHui6eSu3k/v9FCkS9jP5cQzUOjgJbNOJpY5ueAA==
            =lNyT
            -----END PGP MESSAGE-----
          fp: A4B4A47A1DB07DE00E8158BE411E23534CA8FAE0
    encrypted_regex: ^(bmcPassword|ca-key.pem|decryptionSecret|hashedPassword|emcoPassword|rootPassword)$
    version: 3.7.1
