apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: machine-4
spec:
    interval: 5m
    chart:
        spec:
            chart: deploy/machine
            sourceRef:
                kind: GitRepository
                name: icn
            interval: 1m
    values:
        machineName: machine-4
        bootMACAddress: 52:54:00:7a:b4:55
        bmcAddress: redfish-virtualmedia://192.168.151.1:8000/redfish/v1/Systems/41d41744-3dc6-453d-a498-dbd795c5d748
        bmcUsername: admin
        bmcPassword: ENC[AES256_GCM,data:9+b5a6NAo1c=,iv:kISqVgISS1Fv4LWCMzYykvExSiTtzmVnfgcW6t3eWrU=,tag:idLERlkBnVaRSY4QTOsM5g==,type:str]
        bmcDisableCertificateVerification: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-17T16:33:25Z"
    mac: ENC[AES256_GCM,data:DjwG1DhPwuzp5+XewdZtmkFIaszMGxll0/vPRzmLOsUW0fJU8ufkaUEIJ9pDdYIt4OF5nhDq5cK0HQ5z9tXPsOMXwq8pL592leXLgqNc0lye9YJOe/jiMsEhfcXJYI3/Wuqm09p/mAR6hCjXMNHMJRzp3012LwcsHkyHADoZKUg=,iv:EvoEqx8o5CNQtdKaxANCYaDA0MZZandoegccoHmVHZk=,tag:nf0f6DQVWa0rvT8uxFO/2w==,type:str]
    pgp:
        - created_at: "2022-03-17T16:33:24Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4SX7nk+q+zPARAAhueKfQLXCLpW6qAVEJvMgUfKugkmA5g+yB8q0vfbcOG1
            qOtW/UmWRydYYOZrQGvuDZQ8MmBrpMUXP0mN0zVCgcUQ1vb2GV0xsyv454D2pSqT
            Qhp/2wx3TgSJ8oFKQhexjUpygJRUboodW1us/qSAwCmcLqgjVhdT2G75Ovm2j+ez
            EW6te7p7Srszg+Sx0uGsJEtqcz9FRwsklNGTBKROfox9n/bMUFSk11pMSmuKnXfd
            MHLxyFt3HIgkIGcLu+AGzYjjZpLn/CvIvDshEFQF/Q8U2TMYUFXLgBSrtlMXxKpu
            TmmsTlRuUscgjA5Jl63P06zl3cqNjFtAkYKkNYwDQBFo0zdldCN7vXEstMeMARQR
            ffOVCFD4kQznUO5BumEGbLLW+uMGG0hVfaudRqESJ99qIAY6MSmzEcQUAvk8sf7O
            U7sekTUa43qXAqPF2dC6dIkxm7n25Wg60yZk/45IhtuvB0lAgvGgy3UEHJL7Y9tI
            1tm7nm7+V2fitx9AaXnFsdyBHyqLmYTfkygMk0BLmGmMB40Z+9Wh/2N2nIwqLyNH
            391GuDxfkCWsw+8X/8l090M1yKiW+NwT5xieaDwBfoiuMbjczVowbAklQsx4cK3h
            xTs2jUcY605i305vlNPUla6Y9BzsKgb+UMBUTzbSK0wZ9BFjeRkErc1I4SSjTpjS
            XgFcS1ZE1uqNN0LCewcMHxkEPPBcL/2/8MLjI4enbBQ/0Ojhu2Kmiwhnk+Isp+Fu
            t5UXVh/nRVil/uXXb/AWgQnNRqhgLIDi2IcAM+UDXuXgpaYqZlObR0+m7BV0PyE=
            =oTQe
            -----END PGP MESSAGE-----
          fp: A4B4A47A1DB07DE00E8158BE411E23534CA8FAE0
    encrypted_regex: ^(bmcPassword|ca-key.pem|decryptionSecret|hashedPassword|emcoPassword|rootPassword)$
    version: 3.7.1
