apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: machine-1
spec:
    interval: 5m
    chart:
        spec:
            chart: deploy/machine
            sourceRef:
                kind: GitRepository
                name: icn
            interval: 1m
    values:
        machineName: machine-1
        bootMACAddress: 52:54:00:c6:75:40
        bmcAddress: redfish-virtualmedia://192.168.151.1:8000/redfish/v1/Systems/ab389bad-2f4a-4eba-b49e-0d649ff3d237
        bmcUsername: admin
        bmcPassword: ENC[AES256_GCM,data:KZgW0h/IGdM=,iv:VWXRmhWPkBeWvLu1zxNNdjrDQa1f0pf5j9/ghIrBpLQ=,tag:m1O0IsyNWuSLAThGZrc2AQ==,type:str]
        bmcDisableCertificateVerification: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-17T16:33:22Z"
    mac: ENC[AES256_GCM,data:JIdvFPL2Nh6k2jYLVH3PO6yZJCGxxY5Fy+Pnt9YWfmoNTgvN7pwvgj+hu8OKKYkpuKb2Zf2GQxIeucqXYpa6z6Rv+qagfeHSCTxd+MKPNNbKz2aEv8BrNg5y6sqrb3YzXNYooYs9KfsKoInPrARSYGBjwCSfjwhVAWPCwIvl9nk=,iv:7pt5NC9Ymxnk/Z2t1zT0T2ivmyU5Mth7otd/BZsSqDE=,tag:OXBDusWj6ppKAo4BMRgsUQ==,type:str]
    pgp:
        - created_at: "2022-03-17T16:33:21Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4SX7nk+q+zPAQ//a3hrs8wbTqEPGqWIU0POq74d5W1k2DTNILo/dVHAWERu
            lw6XOZyG+eqKfu39qffVGRDzgL+Lb3lJxY6qPCHVNrxtNpFqthRpx0Oojb1Mo5+l
            tnv4tYBtpp9Pk7fr1zC24qee+Tv23CDDeggZVTLWnO6Foi5fGKPqFciyc/cesOuq
            xKOjCrlWE64SLaarfRlrjxrSJ5aMbcaERQZphgrU+NQyqaRti9Ipzpo1ZUkUYnzT
            xfhWjt1BiNeNc2aIhZN9NrkJZlJXoc7GSjVvcmp+vs6qELr1kD4536/Ad/yO3Lxk
            phOJmnVYWTj7L+R8uwpmcjJG4KNEetjvrHBHy3WMdtN/fD7EAsXTnYDNzhIJ3zXB
            Yc8h/nu98vdO/boVHxwGi1/Q+X69YHQVbz65JTqAYErURCzXXCmR1aV6MkqCJ1tH
            aZz3agHEm3UKCHXDtKgy35Iod7JrtgEbsp074mgruQFfN8Bg/1EEJXN9UMDsu/cx
            tAsj5cUgeaO/+3EnEFhk+SkpW0iT3wxcHW2dSl8/qPwm0Vt9pn4qZ36YGgQ2hmG8
            x6JUL34196LshGH3Q+9GG+W6lZY5etbZdrUOKbS7ny3zqn7+THozlYm3xv4o5E1Y
            8Q669O9j8BtTGjMf/WtXg93Qb5t1iKjIB2Wsa0D81025i2olSd9HSXGNJ3TZw8zS
            XgFbP4sUFiiRQceAh2RFG2RKLdrPw4vkDistr644YxAz3I5kKqT1NphojjcV9xhH
            oTblkEra6FWh88f9LAsa5ohPNGDAgc85UCJlqzjnn4FYnvayFfkArQZOMTNtgxo=
            =BJfD
            -----END PGP MESSAGE-----
          fp: A4B4A47A1DB07DE00E8158BE411E23534CA8FAE0
    encrypted_regex: ^(bmcPassword|ca-key.pem|decryptionSecret|hashedPassword|emcoPassword|rootPassword)$
    version: 3.7.1
