apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: machine-2
spec:
    interval: 5m
    chart:
        spec:
            chart: deploy/machine
            sourceRef:
                kind: GitRepository
                name: icn
            interval: 1m
    values:
        machineName: machine-2
        bootMACAddress: 52:54:00:6f:d6:97
        bmcAddress: redfish-virtualmedia://192.168.151.1:8000/redfish/v1/Systems/8d747997-dcd1-42ca-9e25-b3eedbe326aa
        bmcUsername: admin
        bmcPassword: ENC[AES256_GCM,data:HFalZ1KklB8=,iv:8sMm2CwwHLNhB9fP2f0csfbUtKm0TQvpDcaO9e35MXk=,tag:TSPmyNCcNNGNCqmCEvKTww==,type:str]
        bmcDisableCertificateVerification: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-08T22:12:11Z"
    mac: ENC[AES256_GCM,data:oSk5HhFOYQTfwlqw3LfyGu8ZN4eUz3CQLN5pa+ZjKgsYlZKpxausVa1vdCj8O8XfxxXv0JR8AQ7swZ98tkobRETZwc+QCTOVOm8U2OeCGnRLjnlS4oTiB9ElFDsIaQGdJgjjJ1J+ohETJeSDp94FUtSURfI1uaz8Ny1BjMope24=,iv:yKLou2oclHzdrLeTGdzxwxGNOOdpurfPUvAU0B5YuCo=,tag:YlqylAALFHkWQSrRYYUZSw==,type:str]
    pgp:
        - created_at: "2022-03-08T22:12:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4SX7nk+q+zPAQ//djAwmFeVsTd2769BpvaLpGDn+kGIaGVOqBIys4QoALrb
            13gBLu7YiVmi0pI8B5gnPGOgChfvtkd0b4ZiVe0fZJ1C/xPf7n3XPRUds5TPkzuO
            b6SBpv8JmnpbrdAj0jXTiGIB1PQ2f41KVFgxk4bcJ4bx+rZdtfxbfrUFuzeEttPH
            6XtG3BgHSV6DPYYAVAibt2PzP8Ov6CqQrIVOKFhbtJwFN04lTYphOam1UTKawo4j
            CoNZhu0aLRjUmpjvjj9zqEngj9AvyWFOw/TVm/u3B0I9e7H5AbwukR7hWZc+eq+2
            vRL2rilcEK7CXWCtp42LcxsoW+u/8mWEfz/l2Sk5+AvvMU6FNuKZuDSf1CtAbTY5
            FPyAQFwTwJGFCBPH5/vQPpXuFaNMS7ILc4k0JWB+7ddOI/0+uI27zvcLYbHpeU4Q
            jmetajDwY/GDzyoSG6Y2H30j3eFtWlyXcpBt42tWGDOcZx3k1sqmTvoJlTE5rcKi
            tjxfFEBYk3XjqptdQVjSf3MrAV754Scof1n7DRkaQFv5mKoDDcTuMT54gnaQuDYv
            GQxqP6nfpHSCaDMFNllnIjFT8KgPs16Q7XSTB5gRSFkruQibeBL1ZOTPy121Uo20
            m6DYarp262h8tGeddeJb3sFzl4zPFmxWaf7hUosefTwbR0ZRGYJ+/6UZZMDwRJjS
            XgFjs1ZPJbI2ce6IKT14w45yogMViusHLP8StgYjKP1fAW3emTZKinGb5kH6Rj8d
            shdhiqdHKDOpTv4K7T4hz3XShWVPdf0XlgSEBe0HsslP2KMwNtnEjBUVOWa+x/Y=
            =nd27
            -----END PGP MESSAGE-----
          fp: A4B4A47A1DB07DE00E8158BE411E23534CA8FAE0
    encrypted_regex: ^(bmcPassword|ca-key.pem|decryptionSecret|hashedPassword|emcoPassword|rootPassword)$
    version: 3.7.1
