apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: machine-3
spec:
    interval: 5m
    chart:
        spec:
            chart: deploy/machine
            sourceRef:
                kind: GitRepository
                name: icn
            interval: 1m
    values:
        machineName: machine-3
        bootMACAddress: 52:54:00:50:63:44
        bmcAddress: redfish-virtualmedia://192.168.121.1:8000/redfish/v1/Systems/ac3527cc-1223-4794-a0a8-3f6a12f69f17
        bmcUsername: admin
        bmcPassword: ENC[AES256_GCM,data:+mI6dysAyaQ=,iv:Jxup8IDhUAI7cGtuBrBhN7mcAOlIk6khKMlz9ET55ZY=,tag:H8XMVIMsqOVtvqW3aoOAQw==,type:str]
        bmcDisableCertificateVerification: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-06T16:16:43Z"
    mac: ENC[AES256_GCM,data:VotG/ipGDZEuzE5OBneWUagBgPu1UWH1UjC3hoSGpkCd1/Cv4V0PYZoctvF+H+3IpHlj3C87ViPedO+pPmGE+hKG4eLicwKrZMc25Y1jWrykssaGe5z6bThHIOOzewJ0F6GXv0MAUyvoKZZA0JY+GhGSbcyS2MzkC6l/oHv/V6U=,iv:YnSmYsLVvkE+yl1CFGenfE4snrfRTNEMpaqYIcAX7/c=,tag:QPQ1XhagPCF48KUIIBRxxw==,type:str]
    pgp:
        - created_at: "2022-04-06T16:16:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA4SX7nk+q+zPARAAn90j/3bwbzOewVZkcnCuNTZAPPZhZcyFw9cXDLOtmEhg
            yXG7XeLX0gmqAADsse3A5onjg33NcViDMYqh1aCLJsZIyY3qMyCMPrrPISimkJAO
            yBzMJmS1igUfYSog+h3/7BU7uE0FeNNFXYdXcX/PmUGa5PGLMWGaaeLWD6MhPfau
            uvETmzTasyuwTsgQjNwyR0JvM6IDLoJtJ5znshFb3Tb907C8i8UkfeX9r95F5af3
            SjEuAwVIKoCqjFyf+cczrtkWuVbj6n0ThkFE13AkSRQmawWqCtALeS4T7YW8GqHx
            ZlsVJs0n2Y0Lh10yt3ltG3mboLWRA9ZV47VyXueQj12m1gJDM5ycmvajUG0M9sx8
            1sXL/GwiYGF2akB6qIHoZGlygqwz+QX13szY8nRTCJJAZp6op5EpRwUbJT0QVFBh
            KVDTxRH2yMtdmn58uJWtfpquQMYZFzJDYkR93rYF8nJtOVLgCp2dQSukQUG/O+Gn
            3YfomFAhlxwrgvwBzT7yxbndEgmfm2CL3IL3m+cwnVIrliekwGr11TlHhDorHlV/
            ZtOEhKkTGYbFyPYmK02qs/Si/5rs6WTChJ+/nyfdVuk/zGdzJBG0hviHwDxEqo5e
            M5SgleLLrgOL3L8L9VWy2DWcHBGCEVkJfc7Mly+MHQgmVwUfjBk53ilTpfw8U1bS
            5gEMtZQZ8D+cvZMoA2OdVR8Fd9g2piNN8l8BWxGwUp1YTC7PqVePcWvRvTnGKejD
            lCWbHcAUnJWtybJlKv0X2rDk9KkimbLlybUfXp4Ym2KIa+L33H06AA==
            =h5zT
            -----END PGP MESSAGE-----
          fp: A4B4A47A1DB07DE00E8158BE411E23534CA8FAE0
    encrypted_regex: ^(bmcPassword|ca-key.pem|decryptionSecret|hashedPassword|emcoPassword|rootPassword)$
    version: 3.7.1
