apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: machine-4
spec:
    interval: 5m
    chart:
        spec:
            chart: deploy/machine
            sourceRef:
                kind: GitRepository
                name: icn
            interval: 1m
    values:
        machineName: machine-4
        bootMACAddress: 52:54:00:7a:b4:55
        bmcAddress: redfish-virtualmedia://192.168.151.1:8000/redfish/v1/Systems/41d41744-3dc6-453d-a498-dbd795c5d748
        bmcUsername: admin
        bmcPassword: ENC[AES256_GCM,data:+1YhU/Ic7ss=,iv:WA5i/Uujwk+NI+AHNgsk1BALO7gA9Le/0Y7cTvR5ol8=,tag:UDjVd7GD+9H3AiuYixkDrg==,type:str]
        bmcDisableCertificateVerification: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-08T22:12:13Z"
    mac: ENC[AES256_GCM,data:NPmVSpeWT9TDT1ywJBfhuV3t2moDItwNslPmw6Y9rqZe5YoMVk/BlPcX5ilsF9V9vkT7yDsUzmCNkJrHOZGwuKNjBlSE6yRygBaEFgRHeEWZwk1f0BsIUCRPdcgACz5GoyorOP5iAMb0dVHtuTX+ef5S4nbntm7kba28G9mlUeo=,iv:iXrUAxQ9dcyQWcpxZL8boQi+O5knJQOS4BTtKzbCxQM=,tag:kd7VnIZtA+1wEwN9tAjZCg==,type:str]
    pgp:
        - created_at: "2022-03-08T22:12:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4SX7nk+q+zPAQ//fl5z1/gWr4aImJMggP5FgyTfIaMph174fs5YM/tH5b+3
            C+8Y2NfDsBXYFi8uX4NN+5dg1sitOZ1rIIYBlxt2pOEf4Z3ClxV5scKaJLaOMwSp
            rIUyYHUpvHEV+d7YhPJOxJlDQ34vxNMNmHBKPjQT1WuOu2yDZQUdVmKmbf1jQddI
            Gjxt1LxLRJZHgbS3Wc0Ff+y2/tvm+ufmuHyGyLkdfeN/+XGJE+Z/4rS4aPImsFfK
            pwhBhwOpOai39gl5v5o+8oC2da9CmTOOtxAAHt2u7fxRJmFZPdtqU5TPPXJdM3dW
            92cHvrWFDFogpmU++mzwSIuZDigeOOtCc8lc8OSdlz5NjONgITlTN7nKQ/JH+8P0
            wYmX1WUc6MknXfdgkjEXpbCCb+IqlsS+i14uTQFtFtqS2Se1CoyDWzNRQOgyFOZ/
            8zxp+6myMuX/Fgcy0pUKbz0wrsEzSIDIaOC0egJBovlShasYaWF+ITxyEX0DZ8zN
            PDybFAH2Bc8Ru+G3hFwjdKIOC96+NYwA9AyXvhhEvFbxhETqz5A+vq8oieL0fN7N
            4sdY0ElWdkkzFzI8qdBrYtIllTRncRQMFUwITK592PU5Vz+44NJjmoQQsrgPRl0L
            s3GR8Czu2phVRmnsWSWlpP6HlzHvoQ5EOCBow5X43/r3LIWW3QszGLGv0I7JsdHS
            XgEmBy0NhXBRv8dvfPFowpNKCQjDYUPjEqdxJ2DXZeZYqEuN7c5NFYGLjuorWQCj
            yhJkK1DTruZjRwQw5PFJHQ7Cxu0tzpAOP9z2ml3QvfNZVY0WIpG6pfH+AT0RklE=
            =aSKM
            -----END PGP MESSAGE-----
          fp: A4B4A47A1DB07DE00E8158BE411E23534CA8FAE0
    encrypted_regex: ^(bmcPassword|ca-key.pem|decryptionSecret|hashedPassword|emcoPassword|rootPassword)$
    version: 3.7.1
