apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: machine-2
spec:
    interval: 5m
    chart:
        spec:
            chart: deploy/machine
            sourceRef:
                kind: GitRepository
                name: icn
            interval: 1m
    values:
        machineName: machine-2
        bootMACAddress: 52:54:00:6f:d6:97
        bmcAddress: redfish-virtualmedia://192.168.121.1:8000/redfish/v1/Systems/8d747997-dcd1-42ca-9e25-b3eedbe326aa
        bmcUsername: admin
        bmcPassword: ENC[AES256_GCM,data:pJ83hqpONus=,iv:5IfSSOdmG1kumDGWIt1R97qT3CCeU/IptUb1G7CTrrE=,tag:9P13m2g4aG3bOj2T0b8iHg==,type:str]
        bmcDisableCertificateVerification: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-06T16:16:40Z"
    mac: ENC[AES256_GCM,data:/vS4M9MtlldNxtpIqWTBBDdDbjsFSEUEv/KtTnVOjp33mG3wylqSVix2FuifI6Abj3RGdr7PKfokn8jb6vTSiZ4ob74tJ4iJQbs0bOk0wGhGL2Lz91k03AHvkcC0KjsWDh3ALaGMsge7K/Ghesb+VMfD4bHMkGp8HWwS20DTUvg=,iv:UkmN+QXr+uUCl6s3XHbTpawZPrl44q8gi56LNRZJa8s=,tag:elFD7IZeLkq0ISbRBARBWw==,type:str]
    pgp:
        - created_at: "2022-04-06T16:16:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA4SX7nk+q+zPARAASlrkIX8aOpgMVuPXqiH0gSkf80xQbnH2Ne5CmpJi7mu5
            a1+7kKxGMt5AqMJ8WYujwj52XO7A9P1i8QRuGn4Wo/KbcobBk5iORlt2yr3xfliD
            krMykbBn5vViKZ+h/zBE5o8QIcGaIdiy009b+tIZLplMUAVHS8zNtE3p79gxDSyS
            eafV7STbE/wdTEMeLhOYZ2ZqpIku+VrltD/Ljij0E68v6OTJDVGTy9Cv6X6HYJzY
            xD+QdJWj5IeeQJYpF8APnt+jX3wQbamQVsj+N+IMKQuEZ27iJEyVHAGMeE0mUzjU
            JCcKAwQh90TrrhJxdlIIdtzjphf8VaGoIo3a7veSFgR7qKhY+hETf4C6Znegentd
            h99GUCXp/H+ZhK/qt2BKzIZN32zC8XwNBbKwcoqr0YEGhfT58WBwh1Rwu8DMZGpP
            YtkfS7S3AgahZwnbsuWpgmqJKwswfd3xFCXitECkGFUuJEsWJm20Vj7jbA0Z/ght
            TSCgDPPLxW06aWZeOw8EEOhpv2xE81rrfbM4uKO7EWpSFlbyibmRW/S88c6HzI4s
            043odp/mHZ0hiPwl2VoENAUnZoQSW/VceyyiyGnNh8GwV7JQ9PaJmwUVnP/4X0LB
            ekrDwM/Vj/aTuKGBm+WWIK1CUkPDc5tS/zbcCDK/Kc6hMqdXDPHbHnHVOfV6pyrS
            5gGM7Ca4HzDQk71Amnnp/L5lWpdq/juzrF8/WPd0WihU/wqIe9gweyon0NsK1wAJ
            xPESTJloXkWze6/NWyHW/47k76annbCdjrPPzB+YLWfNteJSq9OSAA==
            =oBuR
            -----END PGP MESSAGE-----
          fp: A4B4A47A1DB07DE00E8158BE411E23534CA8FAE0
    encrypted_regex: ^(bmcPassword|ca-key.pem|decryptionSecret|hashedPassword|emcoPassword|rootPassword)$
    version: 3.7.1
