# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: reload facts
  setup:

- name: build cleanup
  make:
    chdir: "{{ git_repo_dest }}"
    target: clean
    params:
      RTE_SDK: "{{ ansible_local.dpdk.dpdk_install_dir }}"

- include_tasks: subtasks/remove_containers.yml
- include_tasks: subtasks/remove_images.yml
- include_tasks: subtasks/remove_additional_folder_structure.yml
- include_tasks: subtasks/remove_certificates_and_keys.yml
- include_tasks: subtasks/remove_docker_daemon_config_file.yml
