# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- include_tasks: subtasks/remove_additional_folder_structure.yml
- include_tasks: subtasks/create_additional_folder_structure.yml

# Certificates
- include_tasks: subtasks/remove_certificates_and_keys.yml
- include_tasks: subtasks/create_empty_cert_and_key.yml

# Configuration files
- include_tasks: subtasks/copy_configs_to_appliance.yml
- include_tasks: subtasks/update_appliance_config_files.yml
- include_tasks: subtasks/copy_logrotate_file.yml
- include_tasks: subtasks/add_firewall_rules.yml

# Align libvirtd and Docker network settings
- include_tasks: subtasks/remove_virbr0_interface.yml
- include_tasks: subtasks/recreate_libvirtd_network_config_file.yml
- include_tasks: subtasks/create_custom_docker_daemon_config_file.yml
- include_tasks: subtasks/create_edgedns_tap.yml

- name: restart Docker
  systemd:
    name: docker
    state: restarted
