# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- include_tasks: cleanup.yml
- include_tasks: prebuild.yml
- include_tasks: build.yml
- include_tasks: deploy.yml
- include_tasks: bringup.yml
