// +build !

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/bpa-operator/pkg/apis/bpa/v1alpha1.Provisioning":       schema_pkg_apis_bpa_v1alpha1_Provisioning(ref),
		"github.com/bpa-operator/pkg/apis/bpa/v1alpha1.ProvisioningSpec":   schema_pkg_apis_bpa_v1alpha1_ProvisioningSpec(ref),
		"github.com/bpa-operator/pkg/apis/bpa/v1alpha1.ProvisioningStatus": schema_pkg_apis_bpa_v1alpha1_ProvisioningStatus(ref),
	}
}

func schema_pkg_apis_bpa_v1alpha1_Provisioning(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Provisioning is the Schema for the provisionings API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/bpa-operator/pkg/apis/bpa/v1alpha1.ProvisioningSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/bpa-operator/pkg/apis/bpa/v1alpha1.ProvisioningStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/bpa-operator/pkg/apis/bpa/v1alpha1.ProvisioningSpec", "github.com/bpa-operator/pkg/apis/bpa/v1alpha1.ProvisioningStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_bpa_v1alpha1_ProvisioningSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ProvisioningSpec defines the desired state of Provisioning",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_bpa_v1alpha1_ProvisioningStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ProvisioningStatus defines the observed state of Provisioning",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
