apiVersion: v1
kind: Namespace
metadata:
    name: metal3
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-14T00:28:28Z"
    mac: ENC[AES256_GCM,data:jJIX4bdrrwThZWYJMG9zRSzf/85nxxBf7SZSw/uQkmhS7sLjEXQRbfUNIZpw/JblQBM7Ar/B+YiTz1pJP3vx6PE67uTbegTHIHQ1XA0+ZXrLlFEMLn4XSTlAQwWTFKXgey8+ogSuwxpjmPQcHMJaTitKJWvJVnPaA6HFyp802I4=,iv:sRbFks+///V+vg3wLldBKAEb/IexHihyXHPswQ5rbOQ=,tag:D0z7ZjQztNT9iaweV8HuEg==,type:str]
    pgp:
        - created_at: "2022-01-14T00:28:26Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4SX7nk+q+zPAQ/5AdqdpaOussjQ3xbKVuEWRanMeFDZHSjdkOxInf7x2NMY
            dmxRW/fWmUqmIkwT6oFW1166o9ZUWjUYMRiseXwVFfl6Erl6d2P06n/pAmWKIbzY
            5tmv4NS+HnGoqD1y98QfiIEonQ4LgNg1V0B14R1C3Ct2bAvXpEkOeGV3N5o0EF6Y
            YUYK22G98G5Br1vaXJ9Jmn6yAzDUZQmtA/qC5gUNPLVvJAncjegGofarNVovJwRR
            LjmRnOPTGbQLoJDS35KfOf8cU9Hp3QWwUTyLgEbggROhfLO5UpVozOLj10M597qd
            MI2HqPkJiPg2PMnSf+8Qw9oCTUyV2+saXK/OmQxHDQeHQBROqJtLUnMRfDdHDkNs
            pCyvcH66jJBHC5e8bB5bDlKMZnXf4cqubBVRj+vdhkPmYuIWRF5DATMe4pTvuGuL
            3CgN4sf0fdUg/Q/El5vSCCqG+cRMtjWbawLGD1YtZEx8XCHERNl9SL8I4ChcFo9N
            TE5s5BzJBuScsKEEW6UPhSSGB4vENQ6sUD1LmhT2sKBh0/0+43L/B6ujG1BJWTPN
            QYGbbNjqgsg4bLE4aKn5UZp1dtC2uVAAkeRiMPn6PUelxwZW4Ei9S+D5jZZxE4ZP
            pT/DZQBAmtdJbKc03eci325IblWKIWRpRhuNE5Mz2+/GYpNM/cy2wcPcX2NSoK7S
            XgGI/ei/LChXeo/J5rfX7ut/FAXQh5G9bBVeAaVXMITc6KXepLiBTAloIFNMzF+E
            g5GqN+yoh6bwd0nmCf5fSIDokVVKn/ozbDtgPle1RjIU0evFga4061XC2mOgilc=
            =WPoJ
            -----END PGP MESSAGE-----
          fp: A4B4A47A1DB07DE00E8158BE411E23534CA8FAE0
    encrypted_regex: ^(bmcPassword|hashedPassword)$
    version: 3.7.1
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
    name: icn
    namespace: metal3
spec:
    gitImplementation: go-git
    interval: 1m0s
    ref:
        branch: master
    timeout: 20s
    url: https://gerrit.akraino.org/r/icn
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-14T00:28:28Z"
    mac: ENC[AES256_GCM,data:jJIX4bdrrwThZWYJMG9zRSzf/85nxxBf7SZSw/uQkmhS7sLjEXQRbfUNIZpw/JblQBM7Ar/B+YiTz1pJP3vx6PE67uTbegTHIHQ1XA0+ZXrLlFEMLn4XSTlAQwWTFKXgey8+ogSuwxpjmPQcHMJaTitKJWvJVnPaA6HFyp802I4=,iv:sRbFks+///V+vg3wLldBKAEb/IexHihyXHPswQ5rbOQ=,tag:D0z7ZjQztNT9iaweV8HuEg==,type:str]
    pgp:
        - created_at: "2022-01-14T00:28:26Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4SX7nk+q+zPAQ/5AdqdpaOussjQ3xbKVuEWRanMeFDZHSjdkOxInf7x2NMY
            dmxRW/fWmUqmIkwT6oFW1166o9ZUWjUYMRiseXwVFfl6Erl6d2P06n/pAmWKIbzY
            5tmv4NS+HnGoqD1y98QfiIEonQ4LgNg1V0B14R1C3Ct2bAvXpEkOeGV3N5o0EF6Y
            YUYK22G98G5Br1vaXJ9Jmn6yAzDUZQmtA/qC5gUNPLVvJAncjegGofarNVovJwRR
            LjmRnOPTGbQLoJDS35KfOf8cU9Hp3QWwUTyLgEbggROhfLO5UpVozOLj10M597qd
            MI2HqPkJiPg2PMnSf+8Qw9oCTUyV2+saXK/OmQxHDQeHQBROqJtLUnMRfDdHDkNs
            pCyvcH66jJBHC5e8bB5bDlKMZnXf4cqubBVRj+vdhkPmYuIWRF5DATMe4pTvuGuL
            3CgN4sf0fdUg/Q/El5vSCCqG+cRMtjWbawLGD1YtZEx8XCHERNl9SL8I4ChcFo9N
            TE5s5BzJBuScsKEEW6UPhSSGB4vENQ6sUD1LmhT2sKBh0/0+43L/B6ujG1BJWTPN
            QYGbbNjqgsg4bLE4aKn5UZp1dtC2uVAAkeRiMPn6PUelxwZW4Ei9S+D5jZZxE4ZP
            pT/DZQBAmtdJbKc03eci325IblWKIWRpRhuNE5Mz2+/GYpNM/cy2wcPcX2NSoK7S
            XgGI/ei/LChXeo/J5rfX7ut/FAXQh5G9bBVeAaVXMITc6KXepLiBTAloIFNMzF+E
            g5GqN+yoh6bwd0nmCf5fSIDokVVKn/ozbDtgPle1RjIU0evFga4061XC2mOgilc=
            =WPoJ
            -----END PGP MESSAGE-----
          fp: A4B4A47A1DB07DE00E8158BE411E23534CA8FAE0
    encrypted_regex: ^(bmcPassword|hashedPassword)$
    version: 3.7.1
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: machine-1
    namespace: metal3
spec:
    interval: 5m
    chart:
        spec:
            chart: deploy/machine
            sourceRef:
                kind: GitRepository
                name: icn
            interval: 1m
    values:
        machineName: machine-1
        bootMACAddress: 52:54:00:c6:75:40
        bmcAddress: ipmi://192.168.151.1:6230
        bmcUsername: admin
        bmcPassword: ENC[AES256_GCM,data:yUB01xLvBgo=,iv:kzL/dq8Q0y4DD9BuM+BxkB/BqpvxoiD/WJCAqQv3iZ8=,tag:Y12m+BAikOXZprDW0xFTGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-14T00:28:28Z"
    mac: ENC[AES256_GCM,data:jJIX4bdrrwThZWYJMG9zRSzf/85nxxBf7SZSw/uQkmhS7sLjEXQRbfUNIZpw/JblQBM7Ar/B+YiTz1pJP3vx6PE67uTbegTHIHQ1XA0+ZXrLlFEMLn4XSTlAQwWTFKXgey8+ogSuwxpjmPQcHMJaTitKJWvJVnPaA6HFyp802I4=,iv:sRbFks+///V+vg3wLldBKAEb/IexHihyXHPswQ5rbOQ=,tag:D0z7ZjQztNT9iaweV8HuEg==,type:str]
    pgp:
        - created_at: "2022-01-14T00:28:26Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4SX7nk+q+zPAQ/5AdqdpaOussjQ3xbKVuEWRanMeFDZHSjdkOxInf7x2NMY
            dmxRW/fWmUqmIkwT6oFW1166o9ZUWjUYMRiseXwVFfl6Erl6d2P06n/pAmWKIbzY
            5tmv4NS+HnGoqD1y98QfiIEonQ4LgNg1V0B14R1C3Ct2bAvXpEkOeGV3N5o0EF6Y
            YUYK22G98G5Br1vaXJ9Jmn6yAzDUZQmtA/qC5gUNPLVvJAncjegGofarNVovJwRR
            LjmRnOPTGbQLoJDS35KfOf8cU9Hp3QWwUTyLgEbggROhfLO5UpVozOLj10M597qd
            MI2HqPkJiPg2PMnSf+8Qw9oCTUyV2+saXK/OmQxHDQeHQBROqJtLUnMRfDdHDkNs
            pCyvcH66jJBHC5e8bB5bDlKMZnXf4cqubBVRj+vdhkPmYuIWRF5DATMe4pTvuGuL
            3CgN4sf0fdUg/Q/El5vSCCqG+cRMtjWbawLGD1YtZEx8XCHERNl9SL8I4ChcFo9N
            TE5s5BzJBuScsKEEW6UPhSSGB4vENQ6sUD1LmhT2sKBh0/0+43L/B6ujG1BJWTPN
            QYGbbNjqgsg4bLE4aKn5UZp1dtC2uVAAkeRiMPn6PUelxwZW4Ei9S+D5jZZxE4ZP
            pT/DZQBAmtdJbKc03eci325IblWKIWRpRhuNE5Mz2+/GYpNM/cy2wcPcX2NSoK7S
            XgGI/ei/LChXeo/J5rfX7ut/FAXQh5G9bBVeAaVXMITc6KXepLiBTAloIFNMzF+E
            g5GqN+yoh6bwd0nmCf5fSIDokVVKn/ozbDtgPle1RjIU0evFga4061XC2mOgilc=
            =WPoJ
            -----END PGP MESSAGE-----
          fp: A4B4A47A1DB07DE00E8158BE411E23534CA8FAE0
    encrypted_regex: ^(bmcPassword|hashedPassword)$
    version: 3.7.1
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: machine-2
    namespace: metal3
spec:
    interval: 5m
    chart:
        spec:
            chart: deploy/machine
            sourceRef:
                kind: GitRepository
                name: icn
            interval: 1m
    values:
        machineName: machine-2
        bootMACAddress: 52:54:00:6f:d6:97
        bmcAddress: ipmi://192.168.151.1:6231
        bmcUsername: admin
        bmcPassword: ENC[AES256_GCM,data:2SwCscZW19I=,iv:DaiMRUjLejRAe2O1prOLep3jH9h4MzMQZrK23285yOI=,tag:9dAvtXDj7+r/l1XfLQniww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-14T00:28:28Z"
    mac: ENC[AES256_GCM,data:jJIX4bdrrwThZWYJMG9zRSzf/85nxxBf7SZSw/uQkmhS7sLjEXQRbfUNIZpw/JblQBM7Ar/B+YiTz1pJP3vx6PE67uTbegTHIHQ1XA0+ZXrLlFEMLn4XSTlAQwWTFKXgey8+ogSuwxpjmPQcHMJaTitKJWvJVnPaA6HFyp802I4=,iv:sRbFks+///V+vg3wLldBKAEb/IexHihyXHPswQ5rbOQ=,tag:D0z7ZjQztNT9iaweV8HuEg==,type:str]
    pgp:
        - created_at: "2022-01-14T00:28:26Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4SX7nk+q+zPAQ/5AdqdpaOussjQ3xbKVuEWRanMeFDZHSjdkOxInf7x2NMY
            dmxRW/fWmUqmIkwT6oFW1166o9ZUWjUYMRiseXwVFfl6Erl6d2P06n/pAmWKIbzY
            5tmv4NS+HnGoqD1y98QfiIEonQ4LgNg1V0B14R1C3Ct2bAvXpEkOeGV3N5o0EF6Y
            YUYK22G98G5Br1vaXJ9Jmn6yAzDUZQmtA/qC5gUNPLVvJAncjegGofarNVovJwRR
            LjmRnOPTGbQLoJDS35KfOf8cU9Hp3QWwUTyLgEbggROhfLO5UpVozOLj10M597qd
            MI2HqPkJiPg2PMnSf+8Qw9oCTUyV2+saXK/OmQxHDQeHQBROqJtLUnMRfDdHDkNs
            pCyvcH66jJBHC5e8bB5bDlKMZnXf4cqubBVRj+vdhkPmYuIWRF5DATMe4pTvuGuL
            3CgN4sf0fdUg/Q/El5vSCCqG+cRMtjWbawLGD1YtZEx8XCHERNl9SL8I4ChcFo9N
            TE5s5BzJBuScsKEEW6UPhSSGB4vENQ6sUD1LmhT2sKBh0/0+43L/B6ujG1BJWTPN
            QYGbbNjqgsg4bLE4aKn5UZp1dtC2uVAAkeRiMPn6PUelxwZW4Ei9S+D5jZZxE4ZP
            pT/DZQBAmtdJbKc03eci325IblWKIWRpRhuNE5Mz2+/GYpNM/cy2wcPcX2NSoK7S
            XgGI/ei/LChXeo/J5rfX7ut/FAXQh5G9bBVeAaVXMITc6KXepLiBTAloIFNMzF+E
            g5GqN+yoh6bwd0nmCf5fSIDokVVKn/ozbDtgPle1RjIU0evFga4061XC2mOgilc=
            =WPoJ
            -----END PGP MESSAGE-----
          fp: A4B4A47A1DB07DE00E8158BE411E23534CA8FAE0
    encrypted_regex: ^(bmcPassword|hashedPassword)$
    version: 3.7.1
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: cluster-icn
    namespace: metal3
spec:
    interval: 5m
    chart:
        spec:
            chart: deploy/cluster
            sourceRef:
                kind: GitRepository
                name: icn
            interval: 1m
    values:
        clusterName: icn
        clusterLabels:
            site: vm
        keepalived:
            interface: ens6
            routerId: 3
        networks:
            baremetal:
                interface: ens6
            provisioning:
                interface: ens5
        userData:
            hashedPassword: ENC[AES256_GCM,data:aZ1DIVYMdBcjxp9DYinn7wsoOgd4JFuS5ptmLuYkf7Y0k7VwrDr+5D4uqVjGYljeIOzELi7TxdUso5z8Xx6czSuumykas9kbi1by085DyTAWYeWcpGxqQvcxmFJIEuRWYfddl6Er8HbejNdFmBgFEAt4YfZr,iv:Pik3lhn3l2wLq4Rr7s3mB+v4KfBxyc/wrOvCoZn/q10=,tag:8qjDc3XX10lkcVhb4kgjxQ==,type:str]
            sshAuthorizedKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDP9Q+b+4tjZuSdL6kDoa2h4ikD3AG6dhxSQQjpUir8Uu2yF6u1WAHq8cBA4KuOnL1eLQqaDRNNeK42Eai7Hi5QlhbNa3MD4hEh8LM1kUDstll6TWUk1LVAX8vcHRPuhHC93yeGWzXLdxSl2jiB0snPyRuNaW9NHz8uNbFsZUtJ3J8pQov85dgCGjdHwhxdDjiprESQLseD5igKz7yhlPdAHrH+1Zmzsng1OUBYsUt62OJnVI0kkvT0H/unFl6rqkmZU8Q14NNqEkwMFGjcOcE95ZPz5Zc9EdjPce0mDLosn9x5gsKe2MairbJLYRp9qQf7JgzOuH2s9gnJ4sklkB83 root@jump
        flux:
            url: https://gerrit.akraino.org/r/icn
            branch: master
            path: ./deploy/site/cluster-icn
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-14T00:28:28Z"
    mac: ENC[AES256_GCM,data:jJIX4bdrrwThZWYJMG9zRSzf/85nxxBf7SZSw/uQkmhS7sLjEXQRbfUNIZpw/JblQBM7Ar/B+YiTz1pJP3vx6PE67uTbegTHIHQ1XA0+ZXrLlFEMLn4XSTlAQwWTFKXgey8+ogSuwxpjmPQcHMJaTitKJWvJVnPaA6HFyp802I4=,iv:sRbFks+///V+vg3wLldBKAEb/IexHihyXHPswQ5rbOQ=,tag:D0z7ZjQztNT9iaweV8HuEg==,type:str]
    pgp:
        - created_at: "2022-01-14T00:28:26Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4SX7nk+q+zPAQ/5AdqdpaOussjQ3xbKVuEWRanMeFDZHSjdkOxInf7x2NMY
            dmxRW/fWmUqmIkwT6oFW1166o9ZUWjUYMRiseXwVFfl6Erl6d2P06n/pAmWKIbzY
            5tmv4NS+HnGoqD1y98QfiIEonQ4LgNg1V0B14R1C3Ct2bAvXpEkOeGV3N5o0EF6Y
            YUYK22G98G5Br1vaXJ9Jmn6yAzDUZQmtA/qC5gUNPLVvJAncjegGofarNVovJwRR
            LjmRnOPTGbQLoJDS35KfOf8cU9Hp3QWwUTyLgEbggROhfLO5UpVozOLj10M597qd
            MI2HqPkJiPg2PMnSf+8Qw9oCTUyV2+saXK/OmQxHDQeHQBROqJtLUnMRfDdHDkNs
            pCyvcH66jJBHC5e8bB5bDlKMZnXf4cqubBVRj+vdhkPmYuIWRF5DATMe4pTvuGuL
            3CgN4sf0fdUg/Q/El5vSCCqG+cRMtjWbawLGD1YtZEx8XCHERNl9SL8I4ChcFo9N
            TE5s5BzJBuScsKEEW6UPhSSGB4vENQ6sUD1LmhT2sKBh0/0+43L/B6ujG1BJWTPN
            QYGbbNjqgsg4bLE4aKn5UZp1dtC2uVAAkeRiMPn6PUelxwZW4Ei9S+D5jZZxE4ZP
            pT/DZQBAmtdJbKc03eci325IblWKIWRpRhuNE5Mz2+/GYpNM/cy2wcPcX2NSoK7S
            XgGI/ei/LChXeo/J5rfX7ut/FAXQh5G9bBVeAaVXMITc6KXepLiBTAloIFNMzF+E
            g5GqN+yoh6bwd0nmCf5fSIDokVVKn/ozbDtgPle1RjIU0evFga4061XC2mOgilc=
            =WPoJ
            -----END PGP MESSAGE-----
          fp: A4B4A47A1DB07DE00E8158BE411E23534CA8FAE0
    encrypted_regex: ^(bmcPassword|hashedPassword)$
    version: 3.7.1
