# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: get worker node name
  block:
  - name: hostname
    command: hostname
    register: hostname_output
  - set_fact:
      k8s_worker_node_name: "{{ hostname_output.stdout | lower }}"

- name: create temporary custom .openness_gitconfig
  include_tasks: ../../../git_repo/tasks/gitconfig_bootstrap.yml

- block:
  - name: build binaries and images
    #    shell: source /etc/profile && KUBE_OVN_MODE=True make build-docker
    shell: . /etc/profile && KUBE_OVN_MODE=True make build-docker
    args:
      chdir: "{{ git_repo_dest }}"
  always:
  - name: remove .openness_gitconfig
    include_tasks: ../../../git_repo/tasks/gitconfig_remove.yml

# since these pods are part of openness' DaemonSet will be recreated after deletion
# this step is for pods to use newly created docker images from previous block
- name: recreate openness pods
  shell: kubectl delete --namespace=openness $(kubectl get pods --namespace=openness --field-selector spec.nodeName={{ k8s_worker_node_name }} -o=NAME | grep -v syslog)
  delegate_to: "{{ groups['controller_group'][0] }}"
  ignore_errors: yes
