# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: remove generated files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - /etc/openness
  - /etc/logrotate.d/edgenode

# built executables are removed during git_repo's role cleanup
# built Docker images are removed during docker's role cleanup
