apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: do-all-global
subjects:
- kind: ServiceAccount
  name: bpa-restapi-agent
  namespace: default
roleRef:
  kind: ClusterRole
  name: do-all
  apiGroup: rbac.authorization.k8s.io
