{{- range $clusterName, $cluster := .Values.clusters }}
---
apiVersion: addons.cluster.x-k8s.io/v1alpha4
kind: ClusterResourceSet
metadata:
  name: {{ $clusterName }}-crs
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ $clusterName }}
  resources:
{{- if eq $cluster.cni "flannel" }}
  - name: {{ $clusterName }}-flannel-addon
    kind: ConfigMap
{{- end }}
{{- if $cluster.flux }}
  - name: {{ $clusterName }}-flux-addon
    kind: ConfigMap
{{- end }}
{{- end }}
