{{- range $clusterName, $cluster := .Values.clusters }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
kind: Metal3MachineTemplate
metadata:
  name: {{ $clusterName }}-workers
spec:
  nodeReuse: false
  template:
    spec:
      automatedCleaningMode: metadata
{{- if $cluster.workersHostSelector }}
      hostSelector:
        {{- toYaml $cluster.workersHostSelector | nindent 8 }}
{{- end }}
{{- if $cluster.networks }}
      dataTemplate:
        name: {{ $clusterName }}-nodepool
{{- end }}
      image:
        checksum: http://172.22.0.1:6180/images/{{ $cluster.imageName }}.md5sum
        url: http://172.22.0.1:6180/images/{{ $cluster.imageName }}
{{- end }}
