# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

dpdk_make_target: "x86_64-native-linuxapp-gcc"
docker_containers_ver: "1.0"
docker_nts_mem_mb_s0: "2048"
docker_nts_mem_mb_s1: "0"
docker_syslog_container_name: "edgenode_syslog-ng_1"
docker_appliance_container_name: "edgenode_appliance_1"
docker_eaa_container_name: "edgenode_eaa_1"
docker_edgednssvr_container_name: "mec-app-edgednssvr"
docker_nts_container_name: "nts"
remote_syslog_ip: "{{ hostvars[groups['controller_group'][0]]['ansible_host'] }}"
enrollment_endpoint: "{{ remote_syslog_ip }}:8081"
download_root_ca_from_controller: true
gopath: "$GOPATH"
