---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kud/deployment_infra/helm/node-feature-discovery
      sourceRef:
        kind: GitRepository
        name: kud
        namespace: flux-system
      interval: 1m
  releaseName: node-feature-discovery
  targetNamespace: kud
  install:
    createNamespace: true
