---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qat-device-plugin
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kud/deployment_infra/helm/qat-device-plugin
      sourceRef:
        kind: GitRepository
        name: kud
        namespace: flux-system
      interval: 1m
  releaseName: qat-device-plugin
  targetNamespace: kud
  install:
    createNamespace: true
