apiVersion: v1
kind: Service
metadata:
  labels:
    app: f5gc-smf
  name: f5gc-smf
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: f5gc-smf-sbi
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
{{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
{{- end }}
  - name: f5gc-smf-n4
    port: 8805
    protocol: UDP
    targetPort: 8805
  selector:
    app: f5gc-smf
