# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: include sriov/common default vars
  include_vars: ../../../sriov/common/defaults/main.yml

# Deploy SRIOV-CNI
- name: deploy CNI
  shell: kubectl create -f ./images/k8s-v1.16/sriov-cni-daemonset.yaml
  args:
    chdir: "{{ sriov_cni.download_dir }}"

# Create temporary directory for SR-IOV network CRD
- name: create temp dir
  tempfile:
    state: directory
    suffix: -sriov-crd
  register: tmp_dir

# Copy SR-IOV network CRD to temporary directory
- name: create SR-IOV network CRD
  copy:
    src: openness-sriov-crd.yml
    dest: "{{ tmp_dir.path }}/openness-sriov-crd.yml"

# Create SR-IOV network
- name: deploy SR-IOV network CRD
  shell: kubectl create -f openness-sriov-crd.yml
  args:
    chdir: "{{ tmp_dir.path }}"

# Create/deploy a sample configMap to be used for SRIOV-DEVICE plugin
- name: deploy dev plugin configMap
  shell: kubectl create -f {{ config_map_path }}
  when: not fpga_sriov_userspace.enabled

# Create/deploy a sample configMap to be used for FPGA USERSPACE SRIOV-DEVICE plugin
- name: deploy FPGA dev plugin configMap
  shell: kubectl create -f {{ fpga_userspace_config_map_path }}
  when: fpga_sriov_userspace.enabled

# Deploy SRIOV-DEVICE Plugin
- name: deploy dev plugin
  shell: kubectl create -f ./deployments/k8s-v1.16/sriovdp-daemonset.yaml
  args:
    chdir: "{{ sriov_dev_plugin.download_dir }}"
