---
apiVersion: addons.cluster.x-k8s.io/v1alpha4
kind: ClusterResourceSet
metadata:
  name: {{ .Values.clusterName }}-crs
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ .Values.clusterName }}
  resources:
  - name: {{ .Values.clusterName }}-podsecurity-addon
    kind: ConfigMap
{{- if eq .Values.cni "calico" }}
  - name: {{ .Values.clusterName }}-calico-addon
    kind: ConfigMap
{{- else if eq .Values.cni "flannel" }}
  - name: {{ .Values.clusterName }}-flannel-addon
    kind: ConfigMap
{{- end }}
{{- if .Values.flux }}
  - name: {{ .Values.clusterName }}-flux-addon
    kind: ConfigMap
{{- end }}
