---
apiVersion: cluster.x-k8s.io/v1alpha4
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: {{ .Values.clusterName }}
    {{- toYaml .Values.clusterLabels | nindent 4 }}
  name: {{ .Values.clusterName }}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      {{- toYaml .Values.podCidrBlocks | nindent 6 }}
    services:
      cidrBlocks:
      {{- toYaml .Values.serviceCidrBlocks | nindent 6 }}
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
    kind: KubeadmControlPlane
    name: {{ .Values.clusterName }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
    kind: Metal3Cluster
    name: {{ .Values.clusterName }}
