---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
kind: Metal3Cluster
metadata:
  name: {{ .Values.clusterName }}
spec:
  controlPlaneEndpoint:
    host: {{ .Values.controlPlaneEndpoint }}
    port: 6443
  noCloudProvider: true
